const INTEGRALS_DATA = {
    section1: [
        { name: "1.1. ∫ (3cos x - 4e^x + 8) dx", integral: "(3\\cos x - 4e^x + 8)\\,dx", answer: "3\\sin x - 4e^x + 8x + C", solution: "$$\\int (3\\cos x - 4e^x + 8)\\,dx = 3\\int \\cos x\\,dx - 4\\int e^x\\,dx + 8\\int dx$$ $$= 3\\sin x - 4e^x + 8x + C$$", practice: "(5\\cos x + 2e^x - 3)\\,dx", practiceAns: "5\\sin x + 2e^x - 3x + C" },
        { name: "1.2. ∫ ((2-x)/x)² dx", integral: "\\left(\\frac{2-x}{x}\\right)^2 dx", answer: "-\\frac{4}{x} - 4\\ln|x| + x + C", solution: "$$\\left(\\frac{2-x}{x}\\right)^2 = \\frac{4 - 4x + x^2}{x^2} = \\frac{4}{x^2} - \\frac{4}{x} + 1$$ $$\\int \\frac{4}{x^2}\\,dx = 4\\cdot\\frac{x^{-1}}{-1} = -\\frac{4}{x}$$ $$\\int \\left(-\\frac{4}{x}\\right)dx = -4\\ln|x|$$ $$\\int 1\\,dx = x$$ $$\\text{Итого: } -\\frac{4}{x} - 4\\ln|x| + x + C$$", practice: "\\left(\\frac{1-x}{x}\\right)^2 dx", practiceAns: "-\\frac{1}{x} - 2\\ln|x| + x + C" },
        { name: "1.3. ∫ (x^{2/3} - x^{1/4}) / x^{1/2} dx", integral: "\\frac{x^{2/3} - x^{1/4}}{x^{1/2}}\\,dx", answer: "\\frac{6}{7}x^{7/6} - \\frac{4}{3}x^{3/4} + C", solution: "$$\\frac{x^{2/3}}{x^{1/2}} = x^{2/3 - 1/2} = x^{1/6}, \\qquad \\frac{x^{1/4}}{x^{1/2}} = x^{1/4 - 1/2} = x^{-1/4}$$ $$\\int x^{1/6}\\,dx = \\frac{x^{7/6}}{7/6} = \\frac{6}{7}x^{7/6}$$ $$\\int x^{-1/4}\\,dx = \\frac{x^{3/4}}{3/4} = \\frac{4}{3}x^{3/4}$$ $$\\text{Итого: } \\frac{6}{7}x^{7/6} - \\frac{4}{3}x^{3/4} + C$$", practice: "\\frac{x - x^{1/3}}{x^{1/2}}\\,dx", practiceAns: "\\frac{2}{3}x^{3/2} - \\frac{6}{5}x^{5/6} + C" },
        { name: "1.4. ∫ (3·2^x - 2·3^x) / 2^x dx", integral: "\\frac{3\\cdot 2^x - 2\\cdot 3^x}{2^x}\\,dx", answer: "3x - \\frac{2\\cdot 3^x}{2^x \\ln(3/2)} + C", solution: "$$\\frac{3\\cdot 2^x - 2\\cdot 3^x}{2^x} = 3 - 2\\cdot\\left(\\frac{3}{2}\\right)^x$$ $$\\int 3\\,dx = 3x$$ $$\\int \\left(\\frac{3}{2}\\right)^x dx = \\frac{(3/2)^x}{\\ln(3/2)}$$ $$\\text{Итого: } 3x - \\frac{2\\cdot 3^x}{2^x \\ln(3/2)} + C$$", practice: "\\frac{4\\cdot 5^x - 5\\cdot 4^x}{5^x}\\,dx", practiceAns: "4x - \\frac{5\\cdot 4^x}{5^x \\ln(4/5)} + C" },
        { name: "1.5. ∫ (1+2x²) / (x²(1+x²)) dx", integral: "\\frac{1+2x^2}{x^2(1+x^2)}\\,dx", answer: "-\\frac{1}{x} + \\arctan x + C", solution: "$$1+2x^2 = (1+x^2) + x^2 \\quad\\Rightarrow\\quad \\frac{1+2x^2}{x^2(1+x^2)} = \\frac{1}{x^2} + \\frac{1}{1+x^2}$$ $$\\int \\frac{dx}{x^2} = -\\frac{1}{x}, \\qquad \\int \\frac{dx}{1+x^2} = \\arctan x$$ $$\\text{Итого: } -\\frac{1}{x} + \\arctan x + C$$", practice: "\\frac{2+x^2}{x^2(1+x^2)}\\,dx", practiceAns: "-\\frac{2}{x} + \\arctan x + C" },
        { name: "1.6. ∫ tg²x dx", integral: "\\tan^2 x\\,dx", answer: "\\operatorname{tg} x - x + C", solution: "$$\\tan^2 x = \\frac{\\sin^2 x}{\\cos^2 x} = \\frac{1 - \\cos^2 x}{\\cos^2 x} = \\frac{1}{\\cos^2 x} - 1$$ $$\\int \\left(\\frac{1}{\\cos^2 x} - 1\\right)dx = \\int \\frac{dx}{\\cos^2 x} - \\int dx = \\operatorname{tg} x - x + C$$", practice: "\\cot^2 x\\,dx", practiceAns: "-\\operatorname{ctg} x - x + C" },
        { name: "1.7. ∫ dx / √(5-3x²)", integral: "\\frac{dx}{\\sqrt{5-3x^2}}", answer: "\\frac{1}{\\sqrt{3}}\\arcsin\\left(\\frac{x\\sqrt{3}}{\\sqrt{5}}\\right) + C", solution: "$$\\sqrt{5-3x^2} = \\sqrt{3}\\;\\sqrt{\\frac{5}{3} - x^2}$$ $$\\int \\frac{dx}{\\sqrt{5-3x^2}} = \\frac{1}{\\sqrt{3}}\\int \\frac{dx}{\\sqrt{\\frac{5}{3} - x^2}} = \\frac{1}{\\sqrt{3}}\\arcsin\\frac{x}{\\sqrt{5/3}}$$ $$= \\frac{1}{\\sqrt{3}}\\arcsin\\frac{x\\sqrt{3}}{\\sqrt{5}} + C$$", practice: "\\frac{dx}{\\sqrt{7-2x^2}}", practiceAns: "\\frac{1}{\\sqrt{2}}\\arcsin\\left(\\frac{x\\sqrt{2}}{\\sqrt{7}}\\right) + C" },
        { name: "1.8. ∫ dx / (cos 2x + sin²x)", integral: "\\frac{dx}{\\cos 2x + \\sin^2 x}", answer: "\\tan x + C", solution: "$$\\cos 2x = 1 - 2\\sin^2 x \\quad\\Rightarrow\\quad \\cos 2x + \\sin^2 x = 1 - \\sin^2 x = \\cos^2 x$$ $$\\int \\frac{dx}{\\cos^2 x} = \\tan x + C$$", practice: "\\frac{dx}{\\cos 2x + 2\\sin^2 x}", practiceAns: "x + C" },
        { name: "1.9. ∫ dx / √(9x²+1)", integral: "\\frac{dx}{\\sqrt{9x^2+1}}", answer: "\\frac{1}{3}\\ln\\left|3x + \\sqrt{9x^2+1}\\right| + C", solution: "$$u = 3x, \\quad du = 3\\,dx \\quad\\Rightarrow\\quad dx = \\frac{du}{3}$$ $$\\int \\frac{dx}{\\sqrt{9x^2+1}} = \\frac{1}{3}\\int \\frac{du}{\\sqrt{u^2+1}} = \\frac{1}{3}\\ln\\left|u + \\sqrt{u^2+1}\\right|$$ $$= \\frac{1}{3}\\ln\\left|3x + \\sqrt{9x^2+1}\\right| + C$$", practice: "\\frac{dx}{\\sqrt{4x^2+1}}", practiceAns: "\\frac{1}{2}\\ln\\left|2x + \\sqrt{4x^2+1}\\right| + C" }
    ],

    section2: [
        { name: "2.1. ∫ cos(4x+2) dx", integral: "\\cos(4x+2)\\,dx", answer: "\\frac{1}{4}\\sin(4x+2) + C", solution: "$$u = 4x+2, \\quad du = 4\\,dx \\quad\\Rightarrow\\quad dx = \\frac{du}{4}$$ $$\\int \\cos(4x+2)\\,dx = \\frac{1}{4}\\int \\cos u\\,du = \\frac{1}{4}\\sin u = \\frac{1}{4}\\sin(4x+2) + C$$", practice: "\\sin(5x-3)\\,dx", practiceAns: "-\\frac{1}{5}\\cos(5x-3) + C" },
        { name: "2.2. ∫ (8-5x)^8 dx", integral: "(8-5x)^8\\,dx", answer: "-\\frac{(8-5x)^9}{45} + C", solution: "$$u = 8-5x, \\quad du = -5\\,dx \\quad\\Rightarrow\\quad dx = -\\frac{du}{5}$$ $$\\int (8-5x)^8\\,dx = -\\frac{1}{5}\\int u^8\\,du = -\\frac{1}{5}\\cdot\\frac{u^9}{9} = -\\frac{(8-5x)^9}{45} + C$$", practice: "(1+2x)^{10}\\,dx", practiceAns: "\\frac{(1+2x)^{11}}{22} + C" },
        { name: "2.3. ∫ 3^{ax} dx", integral: "3^{ax}\\,dx", answer: "\\frac{3^{ax}}{a\\ln 3} + C", solution: "$$u = ax, \\quad du = a\\,dx \\quad\\Rightarrow\\quad dx = \\frac{du}{a}$$ $$\\int 3^{ax}\\,dx = \\frac{1}{a}\\int 3^u\\,du = \\frac{1}{a}\\cdot\\frac{3^u}{\\ln 3} = \\frac{3^{ax}}{a\\ln 3} + C$$", practice: "2^{5x}\\,dx", practiceAns: "\\frac{2^{5x}}{5\\ln 2} + C" },
        { name: "2.4. ∫ dx / √(4x²+1)", integral: "\\frac{dx}{\\sqrt{4x^2+1}}", answer: "\\frac{1}{2}\\ln\\left|2x + \\sqrt{4x^2+1}\\right| + C", solution: "$$u = 2x, \\quad du = 2\\,dx \\quad\\Rightarrow\\quad dx = \\frac{du}{2}$$ $$\\int \\frac{dx}{\\sqrt{4x^2+1}} = \\frac{1}{2}\\int \\frac{du}{\\sqrt{u^2+1}} = \\frac{1}{2}\\ln\\left|u + \\sqrt{u^2+1}\\right|$$ $$= \\frac{1}{2}\\ln\\left|2x + \\sqrt{4x^2+1}\\right| + C$$", practice: "\\frac{dx}{\\sqrt{9x^2+4}}", practiceAns: "\\frac{1}{3}\\ln\\left|3x + \\sqrt{9x^2+4}\\right| + C" },
        { name: "2.5. ∫ dx / √(9-16x²)", integral: "\\frac{dx}{\\sqrt{9-16x^2}}", answer: "\\frac{1}{4}\\arcsin\\frac{4x}{3} + C", solution: "$$u = 4x, \\quad du = 4\\,dx \\quad\\Rightarrow\\quad dx = \\frac{du}{4}$$ $$\\int \\frac{dx}{\\sqrt{9-16x^2}} = \\frac{1}{4}\\int \\frac{du}{\\sqrt{9-u^2}} = \\frac{1}{4}\\arcsin\\frac{u}{3} = \\frac{1}{4}\\arcsin\\frac{4x}{3} + C$$", practice: "\\frac{dx}{\\sqrt{16-25x^2}}", practiceAns: "\\frac{1}{5}\\arcsin\\frac{5x}{4} + C" },
        { name: "2.6. ∫ dx / sin²(7x)", integral: "\\frac{dx}{\\sin^2 7x}", answer: "-\\frac{1}{7}\\cot 7x + C", solution: "$$u = 7x, \\quad du = 7\\,dx \\quad\\Rightarrow\\quad dx = \\frac{du}{7}$$ $$\\int \\frac{dx}{\\sin^2 7x} = \\frac{1}{7}\\int \\csc^2 u\\,du = -\\frac{1}{7}\\cot u = -\\frac{1}{7}\\cot 7x + C$$", practice: "\\frac{dx}{\\cos^2 3x}", practiceAns: "\\frac{1}{3}\\tan 3x + C" },
        { name: "2.7. ∫ x²·∛(x³+2) dx", integral: "x^2\\sqrt[3]{x^3+2}\\,dx", answer: "\\frac{1}{4}(x^3+2)^{4/3} + C", solution: "$$t = x^3+2, \\quad dt = 3x^2\\,dx \\quad\\Rightarrow\\quad x^2\\,dx = \\frac{dt}{3}$$ $$\\int x^2\\sqrt[3]{x^3+2}\\,dx = \\frac{1}{3}\\int t^{1/3}\\,dt = \\frac{1}{3}\\cdot\\frac{3}{4}t^{4/3} = \\frac{1}{4}(x^3+2)^{4/3} + C$$", practice: "x\\sqrt{x^2+1}\\,dx", practiceAns: "\\frac{1}{3}(x^2+1)^{3/2} + C" },
        { name: "2.8. ∫ 4x / (3-5x²) dx", integral: "\\frac{4x}{3-5x^2}\\,dx", answer: "-\\frac{2}{5}\\ln|3-5x^2| + C", solution: "$$t = 3-5x^2, \\quad dt = -10x\\,dx \\quad\\Rightarrow\\quad 4x\\,dx = -\\frac{4}{10}dt = -\\frac{2}{5}dt$$ $$\\int \\frac{4x}{3-5x^2}\\,dx = -\\frac{2}{5}\\int \\frac{dt}{t} = -\\frac{2}{5}\\ln|t| = -\\frac{2}{5}\\ln|3-5x^2| + C$$", practice: "\\frac{x}{1-x^2}\\,dx", practiceAns: "-\\frac{1}{2}\\ln|1-x^2| + C" },
        { name: "2.9. ∫ e^x / √(2e^x+5) dx", integral: "\\frac{e^x}{\\sqrt{2e^x+5}}\\,dx", answer: "\\sqrt{2e^x+5} + C", solution: "$$t = 2e^x+5, \\quad dt = 2e^x\\,dx \\quad\\Rightarrow\\quad e^x\\,dx = \\frac{dt}{2}$$ $$\\int \\frac{e^x}{\\sqrt{2e^x+5}}\\,dx = \\frac{1}{2}\\int t^{-1/2}\\,dt = \\frac{1}{2}\\cdot 2t^{1/2} = \\sqrt{2e^x+5} + C$$", practice: "\\frac{e^x}{1+e^x}\\,dx", practiceAns: "\\ln(1+e^x) + C" },
        { name: "2.10. ∫ (sin x + 2) / cos²x dx", integral: "\\frac{\\sin x + 2}{\\cos^2 x}\\,dx", answer: "\\frac{1}{\\cos x} + 2\\tan x + C", solution: "$$\\int \\frac{\\sin x + 2}{\\cos^2 x}\\,dx = \\int \\frac{\\sin x}{\\cos^2 x}\\,dx + 2\\int \\frac{dx}{\\cos^2 x}$$ $$\\text{Первый: } t = \\cos x,\\; dt = -\\sin x\\,dx \\quad\\Rightarrow\\quad -\\int \\frac{dt}{t^2} = \\frac{1}{t} = \\frac{1}{\\cos x}$$ $$\\text{Второй: } 2\\int \\sec^2 x\\,dx = 2\\tan x$$ $$\\text{Итого: } \\frac{1}{\\cos x} + 2\\tan x + C$$", practice: "\\frac{\\cos x - 3}{\\sin^2 x}\\,dx", practiceAns: "-\\frac{1}{\\sin x} + 3\\cot x + C" },
        { name: "2.11. ∫ ctg(4x) dx", integral: "\\cot(4x)\\,dx", answer: "\\frac{1}{4}\\ln|\\sin(4x)| + C", solution: "$$\\cot(4x) = \\frac{\\cos(4x)}{\\sin(4x)}$$ $$t = \\sin(4x), \\quad dt = 4\\cos(4x)\\,dx \\quad\\Rightarrow\\quad \\cos(4x)\\,dx = \\frac{dt}{4}$$ $$\\int \\frac{\\cos(4x)}{\\sin(4x)}\\,dx = \\frac{1}{4}\\int \\frac{dt}{t} = \\frac{1}{4}\\ln|t| = \\frac{1}{4}\\ln|\\sin(4x)| + C$$", practice: "\\tan(2x)\\,dx", practiceAns: "-\\frac{1}{2}\\ln|\\cos(2x)| + C" },
        { name: "2.12. ∫ √(ln x + 5) / x dx", integral: "\\frac{\\sqrt{\\ln x + 5}}{x}\\,dx", answer: "\\frac{2}{3}(\\ln x + 5)^{3/2} + C", solution: "$$t = \\ln x + 5, \\quad dt = \\frac{dx}{x}$$ $$\\int \\sqrt{\\ln x + 5}\\cdot\\frac{dx}{x} = \\int t^{1/2}\\,dt = \\frac{2}{3}t^{3/2} = \\frac{2}{3}(\\ln x + 5)^{3/2} + C$$", practice: "\\frac{\\ln^2 x}{x}\\,dx", practiceAns: "\\frac{\\ln^3 x}{3} + C" },
        { name: "2.13. ∫ (arctg³x - 2) / (1+x²) dx", integral: "\\frac{\\arctan^3 x - 2}{1+x^2}\\,dx", answer: "\\frac{\\arctan^4 x}{4} - 2\\arctan x + C", solution: "$$t = \\arctan x, \\quad dt = \\frac{dx}{1+x^2}$$ $$\\int \\frac{\\arctan^3 x - 2}{1+x^2}\\,dx = \\int (t^3 - 2)\\,dt = \\frac{t^4}{4} - 2t = \\frac{\\arctan^4 x}{4} - 2\\arctan x + C$$", practice: "\\frac{\\arctan x}{1+x^2}\\,dx", practiceAns: "\\frac{\\arctan^2 x}{2} + C" },
        { name: "2.14. ∫ e^{arccos(2x)} / √(1-4x²) dx", integral: "\\frac{e^{\\arccos(2x)}}{\\sqrt{1-4x^2}}\\,dx", answer: "-\\frac{1}{2}e^{\\arccos(2x)} + C", solution: "$$t = \\arccos(2x), \\quad dt = -\\frac{2}{\\sqrt{1-4x^2}}\\,dx \\quad\\Rightarrow\\quad \\frac{dx}{\\sqrt{1-4x^2}} = -\\frac{dt}{2}$$ $$\\int \\frac{e^{\\arccos(2x)}}{\\sqrt{1-4x^2}}\\,dx = -\\frac{1}{2}\\int e^t\\,dt = -\\frac{1}{2}e^t = -\\frac{1}{2}e^{\\arccos(2x)} + C$$", practice: "\\frac{e^{\\arcsin x}}{\\sqrt{1-x^2}}\\,dx", practiceAns: "e^{\\arcsin x} + C" },
        { name: "2.15. ∫ dx / (ln²x · x)", integral: "\\frac{dx}{\\ln^2 x \\cdot x}", answer: "-\\frac{1}{\\ln x} + C", solution: "$$t = \\ln x, \\quad dt = \\frac{dx}{x}$$ $$\\int \\frac{dx}{\\ln^2 x \\cdot x} = \\int \\frac{dt}{t^2} = -\\frac{1}{t} = -\\frac{1}{\\ln x} + C$$", practice: "\\frac{dx}{x\\ln x}", practiceAns: "\\ln|\\ln x| + C" },
        { name: "2.16. ∫ sin x / √(cos x) dx", integral: "\\frac{\\sin x}{\\sqrt{\\cos x}}\\,dx", answer: "-2\\sqrt{\\cos x} + C", solution: "$$t = \\cos x, \\quad dt = -\\sin x\\,dx \\quad\\Rightarrow\\quad \\sin x\\,dx = -dt$$ $$\\int \\frac{\\sin x}{\\sqrt{\\cos x}}\\,dx = -\\int t^{-1/2}\\,dt = -2t^{1/2} = -2\\sqrt{\\cos x} + C$$", practice: "\\sin x\\cos^3 x\\,dx", practiceAns: "-\\frac{\\cos^4 x}{4} + C" },
        { name: "2.17. ∫ e^{arccos(2x)} / √(1-4x²) dx", integral: "\\frac{e^{\\arccos(2x)}}{\\sqrt{1-4x^2}}\\,dx", answer: "-\\frac{1}{2}e^{\\arccos(2x)} + C", solution: "$$t = \\arccos(2x), \\quad dt = -\\frac{2}{\\sqrt{1-4x^2}}\\,dx \\quad\\Rightarrow\\quad \\frac{dx}{\\sqrt{1-4x^2}} = -\\frac{dt}{2}$$ $$\\int \\frac{e^{\\arccos(2x)}}{\\sqrt{1-4x^2}}\\,dx = -\\frac{1}{2}\\int e^t\\,dt = -\\frac{1}{2}e^{\\arccos(2x)} + C$$", practice: "\\frac{\\arcsin^2 x}{\\sqrt{1-x^2}}\\,dx", practiceAns: "\\frac{\\arcsin^3 x}{3} + C" },
        { name: "2.18. ∫ √x / (1+x) dx", integral: "\\frac{\\sqrt{x}}{1+x}\\,dx", answer: "2\\sqrt{x} - 2\\arctan(\\sqrt{x}) + C", solution: "$$t = \\sqrt{x}, \\quad x = t^2, \\quad dx = 2t\\,dt$$ $$\\int \\frac{\\sqrt{x}}{1+x}\\,dx = \\int \\frac{t}{1+t^2}\\cdot 2t\\,dt = 2\\int \\frac{t^2}{1+t^2}\\,dt = 2\\int\\left(1 - \\frac{1}{1+t^2}\\right)dt$$ $$= 2t - 2\\arctan t = 2\\sqrt{x} - 2\\arctan(\\sqrt{x}) + C$$", practice: "\\frac{dx}{\\sqrt{x}(1+x)}", practiceAns: "2\\arctan\\sqrt{x} + C" },
        { name: "2.19. ∫ 3 dx / (x√(2x+1))", integral: "\\frac{3\\,dx}{x\\sqrt{2x+1}}", answer: "3\\ln\\left|\\frac{\\sqrt{2x+1}-1}{\\sqrt{2x+1}+1}\\right| + C", solution: "$$t = \\sqrt{2x+1}, \\quad x = \\frac{t^2-1}{2}, \\quad dx = t\\,dt$$ $$\\int \\frac{3\\,dx}{x\\sqrt{2x+1}} = 3\\int \\frac{t\\,dt}{\\frac{t^2-1}{2}\\cdot t} = 6\\int \\frac{dt}{t^2-1} = 6\\cdot\\frac{1}{2}\\ln\\left|\\frac{t-1}{t+1}\\right|$$ $$= 3\\ln\\left|\\frac{\\sqrt{2x+1}-1}{\\sqrt{2x+1}+1}\\right| + C$$", practice: "\\frac{dx}{x\\sqrt{x+1}}", practiceAns: "\\ln\\left|\\frac{\\sqrt{x+1}-1}{\\sqrt{x+1}+1}\\right| + C" },
        { name: "2.20. ∫ dx / (√x + ∜x)", integral: "\\frac{dx}{\\sqrt{x} + \\sqrt[4]{x}}", answer: "2\\sqrt{x} - 4\\sqrt[4]{x} + 4\\ln|\\sqrt[4]{x}+1| + C", solution: "$$x = t^4, \\quad dx = 4t^3\\,dt, \\quad \\sqrt{x} = t^2, \\quad \\sqrt[4]{x} = t$$ $$\\int \\frac{dx}{\\sqrt{x} + \\sqrt[4]{x}} = \\int \\frac{4t^3}{t^2+t}\\,dt = 4\\int \\frac{t^3}{t(t+1)}\\,dt = 4\\int \\frac{t^2}{t+1}\\,dt$$ $$\\frac{t^2}{t+1} = t - 1 + \\frac{1}{t+1}$$ $$4\\int\\left(t - 1 + \\frac{1}{t+1}\\right)dt = 4\\left(\\frac{t^2}{2} - t + \\ln|t+1|\\right) = 2t^2 - 4t + 4\\ln|t+1|$$ $$= 2\\sqrt{x} - 4\\sqrt[4]{x} + 4\\ln|\\sqrt[4]{x}+1| + C$$", practice: "\\frac{dx}{\\sqrt{x}-\\sqrt[4]{x}}", practiceAns: "2\\sqrt{x} + 4\\sqrt[4]{x} + 4\\ln|\\sqrt[4]{x}-1| + C" },
        { name: "2.21. ∫ dx / √(1+e^x)", integral: "\\frac{dx}{\\sqrt{1+e^x}}", answer: "\\ln\\left|\\frac{\\sqrt{1+e^x}-1}{\\sqrt{1+e^x}+1}\\right| + C", solution: "$$t = \\sqrt{1+e^x}, \\quad t^2 = 1+e^x, \\quad 2t\\,dt = e^x\\,dx = (t^2-1)\\,dx$$ $$dx = \\frac{2t}{t^2-1}\\,dt$$ $$\\int \\frac{dx}{\\sqrt{1+e^x}} = \\int \\frac{1}{t}\\cdot\\frac{2t}{t^2-1}\\,dt = 2\\int \\frac{dt}{t^2-1} = \\ln\\left|\\frac{t-1}{t+1}\\right|$$ $$= \\ln\\left|\\frac{\\sqrt{1+e^x}-1}{\\sqrt{1+e^x}+1}\\right| + C$$", practice: "\\frac{e^x\\,dx}{1+e^x}", practiceAns: "\\ln(1+e^x) + C" }
    ],

    section3: [
        { name: "3.1. ∫ (3-x)·sin(2x) dx", integral: "(3-x)\\sin(2x)\\,dx", answer: "\\frac{x-3}{2}\\cos(2x) - \\frac{1}{4}\\sin(2x) + C", solution: "$$u = 3-x, \\quad dv = \\sin(2x)\\,dx$$ $$du = -dx, \\quad v = -\\frac{1}{2}\\cos(2x)$$ $$\\int u\\,dv = uv - \\int v\\,du = (3-x)\\left(-\\frac{1}{2}\\cos 2x\\right) - \\int\\left(-\\frac{1}{2}\\cos 2x\\right)(-1)\\,dx$$ $$= \\frac{x-3}{2}\\cos 2x - \\frac{1}{2}\\int \\cos 2x\\,dx = \\frac{x-3}{2}\\cos 2x - \\frac{1}{4}\\sin 2x + C$$", practice: "x\\cos x\\,dx", practiceAns: "x\\sin x + \\cos x + C" },
        { name: "3.2. ∫ x²·e^{-x} dx", integral: "x^2 e^{-x}\\,dx", answer: "-e^{-x}(x^2+2x+2) + C", solution: "$$\\text{Первый раз: } u = x^2, \\; dv = e^{-x}dx \\quad\\Rightarrow\\quad du = 2x\\,dx, \\; v = -e^{-x}$$ $$\\int x^2 e^{-x}dx = -x^2 e^{-x} + 2\\int x e^{-x}dx$$ $$\\text{Второй раз: } u = x, \\; dv = e^{-x}dx \\quad\\Rightarrow\\quad du = dx, \\; v = -e^{-x}$$ $$\\int x e^{-x}dx = -x e^{-x} + \\int e^{-x}dx = -x e^{-x} - e^{-x}$$ $$\\text{Итого: } -x^2 e^{-x} + 2(-x e^{-x} - e^{-x}) = -e^{-x}(x^2+2x+2) + C$$", practice: "x^2 e^x\\,dx", practiceAns: "e^x(x^2-2x+2) + C" },
        { name: "3.3. ∫ x²·ln(1+x) dx", integral: "x^2\\ln(1+x)\\,dx", answer: "\\frac{x^3}{3}\\ln(1+x) - \\frac{x^3}{9} + \\frac{x^2}{6} - \\frac{x}{3} + \\frac{1}{3}\\ln|x+1| + C", solution: "$$u = \\ln(1+x), \\quad dv = x^2\\,dx \\quad\\Rightarrow\\quad du = \\frac{dx}{1+x}, \\; v = \\frac{x^3}{3}$$ $$\\int x^2\\ln(1+x)\\,dx = \\frac{x^3}{3}\\ln(1+x) - \\frac{1}{3}\\int \\frac{x^3}{1+x}\\,dx$$ $$\\frac{x^3}{1+x} = x^2 - x + 1 - \\frac{1}{1+x}$$ $$\\int \\frac{x^3}{1+x}\\,dx = \\frac{x^3}{3} - \\frac{x^2}{2} + x - \\ln|1+x|$$ $$\\text{Итого: } \\frac{x^3}{3}\\ln(1+x) - \\frac{x^3}{9} + \\frac{x^2}{6} - \\frac{x}{3} + \\frac{1}{3}\\ln|x+1| + C$$", practice: "x\\ln x\\,dx", practiceAns: "\\frac{x^2}{2}\\ln x - \\frac{x^2}{4} + C" },
        { name: "3.4. ∫ arcsin(3x) dx", integral: "\\arcsin(3x)\\,dx", answer: "x\\arcsin(3x) + \\frac{1}{3}\\sqrt{1-9x^2} + C", solution: "$$u = \\arcsin(3x), \\quad dv = dx \\quad\\Rightarrow\\quad du = \\frac{3}{\\sqrt{1-9x^2}}dx, \\; v = x$$ $$\\int \\arcsin(3x)\\,dx = x\\arcsin(3x) - 3\\int \\frac{x}{\\sqrt{1-9x^2}}\\,dx$$ $$t = 1-9x^2, \\quad dt = -18x\\,dx \\quad\\Rightarrow\\quad x\\,dx = -\\frac{dt}{18}$$ $$-3\\int \\frac{x}{\\sqrt{1-9x^2}}\\,dx = -3\\cdot\\left(-\\frac{1}{18}\\right)\\int t^{-1/2}dt = \\frac{1}{6}\\cdot 2t^{1/2} = \\frac{1}{3}\\sqrt{1-9x^2}$$ $$\\text{Итого: } x\\arcsin(3x) + \\frac{1}{3}\\sqrt{1-9x^2} + C$$", practice: "\\arctan x\\,dx", practiceAns: "x\\arctan x - \\frac{1}{2}\\ln(1+x^2) + C" },
        { name: "3.5. ∫ x·arcctg(x) dx", integral: "x\\cdot\\operatorname{arcctg} x\\,dx", answer: "\\frac{x^2+1}{2}\\operatorname{arcctg} x + \\frac{x}{2} - \\frac{1}{2}\\arctan x + C", solution: "$$u = \\operatorname{arcctg} x, \\quad dv = x\\,dx \\quad\\Rightarrow\\quad du = -\\frac{dx}{1+x^2}, \\; v = \\frac{x^2}{2}$$ $$\\int x\\operatorname{arcctg} x\\,dx = \\frac{x^2}{2}\\operatorname{arcctg} x + \\frac{1}{2}\\int \\frac{x^2}{1+x^2}\\,dx$$ $$\\frac{x^2}{1+x^2} = 1 - \\frac{1}{1+x^2}$$ $$\\frac{1}{2}\\int\\left(1 - \\frac{1}{1+x^2}\\right)dx = \\frac{1}{2}\\left(x - \\arctan x\\right)$$ $$\\text{Итого: } \\frac{x^2}{2}\\operatorname{arcctg} x + \\frac{x}{2} - \\frac{1}{2}\\arctan x + C$$", practice: "x\\arctan x\\,dx", practiceAns: "\\frac{x^2+1}{2}\\arctan x - \\frac{x}{2} + C" },
        { name: "3.6. ∫ sin(ln x) dx", integral: "\\sin(\\ln x)\\,dx", answer: "\\frac{x}{2}\\bigl(\\sin(\\ln x) - \\cos(\\ln x)\\bigr) + C", solution: "$$I = \\int \\sin(\\ln x)\\,dx$$ $$\\text{Первый раз: } u = \\sin(\\ln x), \\; dv = dx \\quad\\Rightarrow\\quad du = \\frac{\\cos(\\ln x)}{x}dx, \\; v = x$$ $$I = x\\sin(\\ln x) - \\int \\cos(\\ln x)\\,dx$$ $$\\text{Второй раз: } u = \\cos(\\ln x), \\; dv = dx \\quad\\Rightarrow\\quad du = -\\frac{\\sin(\\ln x)}{x}dx, \\; v = x$$ $$\\int \\cos(\\ln x)\\,dx = x\\cos(\\ln x) + \\int \\sin(\\ln x)\\,dx = x\\cos(\\ln x) + I$$ $$I = x\\sin(\\ln x) - x\\cos(\\ln x) - I \\quad\\Rightarrow\\quad 2I = x(\\sin(\\ln x) - \\cos(\\ln x))$$ $$I = \\frac{x}{2}\\bigl(\\sin(\\ln x) - \\cos(\\ln x)\\bigr) + C$$", practice: "\\cos(\\ln x)\\,dx", practiceAns: "\\frac{x}{2}\\bigl(\\sin(\\ln x) + \\cos(\\ln x)\\bigr) + C" }
    ],

    section4: [
        { name: "4.1. ∫ dx / √(5-2x+x²)", integral: "\\frac{dx}{\\sqrt{x^2-2x+5}}", answer: "\\ln\\left|x-1 + \\sqrt{x^2-2x+5}\\right| + C", solution: "$$x^2 - 2x + 5 = (x-1)^2 + 4$$ $$t = x-1, \\quad dt = dx$$ $$\\int \\frac{dx}{\\sqrt{(x-1)^2+4}} = \\int \\frac{dt}{\\sqrt{t^2+4}} = \\ln\\left|t + \\sqrt{t^2+4}\\right|$$ $$= \\ln\\left|x-1 + \\sqrt{x^2-2x+5}\\right| + C$$", practice: "\\frac{dx}{\\sqrt{x^2+4x+5}}", practiceAns: "\\ln\\left|x+2 + \\sqrt{x^2+4x+5}\\right| + C" },
        { name: "4.2. ∫ dx / (9x²-6x+2)", integral: "\\frac{dx}{9x^2-6x+2}", answer: "\\frac{1}{3}\\arctan(3x-1) + C", solution: "$$9x^2 - 6x + 2 = (3x-1)^2 + 1$$ $$t = 3x-1, \\quad dt = 3\\,dx \\quad\\Rightarrow\\quad dx = \\frac{dt}{3}$$ $$\\int \\frac{dx}{(3x-1)^2+1} = \\frac{1}{3}\\int \\frac{dt}{t^2+1} = \\frac{1}{3}\\arctan t = \\frac{1}{3}\\arctan(3x-1) + C$$", practice: "\\frac{dx}{x^2+2x+2}", practiceAns: "\\arctan(x+1) + C" }
    ],

    section5: [
        { name: "5.1. ∫ (x+2) / (x²+2x-3) dx", integral: "\\frac{x+2}{x^2+2x-3}\\,dx", answer: "\\frac{1}{2}\\ln|x^2+2x-3| + \\frac{1}{4}\\ln\\left|\\frac{x-1}{x+3}\\right| + C", solution: "$$\\text{Производная знаменателя: } (x^2+2x-3)' = 2x+2$$ $$x+2 = \\frac{1}{2}(2x+2) + 1$$ $$\\int \\frac{x+2}{x^2+2x-3}\\,dx = \\frac{1}{2}\\int \\frac{2x+2}{x^2+2x-3}\\,dx + \\int \\frac{dx}{x^2+2x-3}$$ $$\\text{Первый: } \\frac{1}{2}\\ln|x^2+2x-3|$$ $$\\text{Второй: } x^2+2x-3 = (x-1)(x+3), \\quad \\frac{1}{(x-1)(x+3)} = \\frac{1}{4}\\left(\\frac{1}{x-1} - \\frac{1}{x+3}\\right)$$ $$\\int \\frac{dx}{x^2+2x-3} = \\frac{1}{4}\\ln\\left|\\frac{x-1}{x+3}\\right|$$ $$\\text{Итого: } \\frac{1}{2}\\ln|x^2+2x-3| + \\frac{1}{4}\\ln\\left|\\frac{x-1}{x+3}\\right| + C$$", practice: "\\frac{x}{x^2+2x+5}\\,dx", practiceAns: "\\frac{1}{2}\\ln(x^2+2x+5) - \\frac{1}{2}\\arctan\\frac{x+1}{2} + C" },
        { name: "5.2. ∫ (x-3) / √(3-2x-x²) dx", integral: "\\frac{x-3}{\\sqrt{3-2x-x^2}}\\,dx", answer: "-\\sqrt{3-2x-x^2} - 4\\arcsin\\left(\\frac{x+1}{2}\\right) + C", solution: "$$\\text{Производная подкоренного: } (3-2x-x^2)' = -2-2x = -2(x+1)$$ $$x-3 = -\\frac{1}{2}(-2x-2) - 4$$ $$\\int \\frac{x-3}{\\sqrt{3-2x-x^2}}\\,dx = -\\frac{1}{2}\\int \\frac{-2x-2}{\\sqrt{3-2x-x^2}}\\,dx - 4\\int \\frac{dx}{\\sqrt{3-2x-x^2}}$$ $$\\text{Первый: } -\\frac{1}{2}\\cdot 2\\sqrt{3-2x-x^2} = -\\sqrt{3-2x-x^2}$$ $$\\text{Второй: } 3-2x-x^2 = 4-(x+1)^2, \\quad \\int \\frac{dx}{\\sqrt{4-(x+1)^2}} = \\arcsin\\frac{x+1}{2}$$ $$\\text{Итого: } -\\sqrt{3-2x-x^2} - 4\\arcsin\\left(\\frac{x+1}{2}\\right) + C$$", practice: "\\frac{x+1}{\\sqrt{1-x^2}}\\,dx", practiceAns: "-\\sqrt{1-x^2} + \\arcsin x + C" }
    ],

    section6: [
        { name: "6.1. ∫ dx / (x√(2+2x-x²))", integral: "\\frac{dx}{x\\sqrt{2+2x-x^2}}", answer: "-\\frac{1}{\\sqrt{2}}\\ln\\left|\\frac{\\sqrt{2}+\\sqrt{2+2x-x^2}}{x}\\right| + C", solution: "$$x = \\frac{1}{t}, \\quad dx = -\\frac{dt}{t^2}$$ $$\\sqrt{2+2x-x^2} = \\sqrt{2+\\frac{2}{t}-\\frac{1}{t^2}} = \\frac{\\sqrt{2t^2+2t-1}}{|t|}$$ $$\\int \\frac{dx}{x\\sqrt{2+2x-x^2}} = \\int \\frac{-dt/t^2}{\\frac{1}{t}\\cdot\\frac{\\sqrt{2t^2+2t-1}}{|t|}} = -\\int \\frac{dt}{\\sqrt{2t^2+2t-1}}$$ $$2t^2+2t-1 = 2\\left(t+\\frac{1}{2}\\right)^2 - \\frac{3}{2}$$ $$-\\int \\frac{dt}{\\sqrt{2t^2+2t-1}} = -\\frac{1}{\\sqrt{2}}\\ln\\left|t+\\frac{1}{2} + \\sqrt{t^2+t-\\frac{1}{2}}\\right|$$ $$= -\\frac{1}{\\sqrt{2}}\\ln\\left|\\frac{1}{x}+\\frac{1}{2} + \\frac{\\sqrt{2+2x-x^2}}{|x|}\\right| = -\\frac{1}{\\sqrt{2}}\\ln\\left|\\frac{\\sqrt{2}+\\sqrt{2+2x-x^2}}{x}\\right| + C$$", practice: "\\frac{dx}{x\\sqrt{x^2+1}}", practiceAns: "-\\ln\\left|\\frac{1+\\sqrt{x^2+1}}{x}\\right| + C" },
        { name: "6.2. ∫ dx / (x√(x²+4x-9))", integral: "\\frac{dx}{x\\sqrt{x^2+4x-9}}", answer: "-\\frac{1}{3}\\arcsin\\left(\\frac{9-2x}{x\\sqrt{13}}\\right) + C", solution: "$$x = \\frac{1}{t}, \\quad dx = -\\frac{dt}{t^2}$$ $$\\sqrt{x^2+4x-9} = \\sqrt{\\frac{1}{t^2}+\\frac{4}{t}-9} = \\frac{\\sqrt{1+4t-9t^2}}{|t|}$$ $$\\int \\frac{dx}{x\\sqrt{x^2+4x-9}} = -\\int \\frac{dt}{\\sqrt{1+4t-9t^2}}$$ $$1+4t-9t^2 = \\frac{13}{9} - 9\\left(t-\\frac{2}{9}\\right)^2$$ $$-\\int \\frac{dt}{\\sqrt{\\frac{13}{9} - 9(t-\\frac{2}{9})^2}} = -\\frac{1}{3}\\arcsin\\left(\\frac{9t-2}{\\sqrt{13}}\\right) = -\\frac{1}{3}\\arcsin\\left(\\frac{9-2x}{x\\sqrt{13}}\\right) + C$$", practice: "\\frac{dx}{x\\sqrt{x^2-1}}", practiceAns: "\\operatorname{arcsec} x + C" }
    ],

    section7: [
        { name: "7.1. ∫ (2x²+4x-11) / ((x-1)(x+3)(x-2)) dx", integral: "\\frac{2x^2+4x-11}{(x-1)(x+3)(x-2)}\\,dx", answer: "\\frac{5}{4}\\ln|x-1| - \\frac{1}{4}\\ln|x+3| + \\ln|x-2| + C", solution: "$$\\frac{2x^2+4x-11}{(x-1)(x+3)(x-2)} = \\frac{A}{x-1} + \\frac{B}{x+3} + \\frac{C}{x-2}$$ $$A = \\left.\\frac{2x^2+4x-11}{(x+3)(x-2)}\\right|_{x=1} = \\frac{2+4-11}{4\\cdot(-1)} = \\frac{-5}{-4} = \\frac{5}{4}$$ $$B = \\left.\\frac{2x^2+4x-11}{(x-1)(x-2)}\\right|_{x=-3} = \\frac{18-12-11}{(-4)(-5)} = \\frac{-5}{20} = -\\frac{1}{4}$$ $$C = \\left.\\frac{2x^2+4x-11}{(x-1)(x+3)}\\right|_{x=2} = \\frac{8+8-11}{1\\cdot 5} = 1$$ $$\\text{Итого: } \\frac{5}{4}\\ln|x-1| - \\frac{1}{4}\\ln|x+3| + \\ln|x-2| + C$$", practice: "\\frac{dx}{(x-1)(x-2)}", practiceAns: "\\ln|x-2| - \\ln|x-1| + C" },
        { name: "7.2. ∫ (x²-3x+2) / (x(x+1)²) dx", integral: "\\frac{x^2-3x+2}{x(x+1)^2}\\,dx", answer: "2\\ln|x| - \\ln|x+1| + \\frac{6}{x+1} + C", solution: "$$\\frac{x^2-3x+2}{x(x+1)^2} = \\frac{A}{x} + \\frac{B}{x+1} + \\frac{D}{(x+1)^2}$$ $$x^2-3x+2 = A(x+1)^2 + Bx(x+1) + Dx$$ $$x=0: \\; 2 = A \\quad\\Rightarrow\\quad A = 2$$ $$x=-1: \\; 1+3+2 = -D \\quad\\Rightarrow\\quad D = -6$$ $$\\text{Коэф. при }x^2: \\; 1 = A+B \\quad\\Rightarrow\\quad B = -1$$ $$\\int\\left(\\frac{2}{x} - \\frac{1}{x+1} - \\frac{6}{(x+1)^2}\\right)dx = 2\\ln|x| - \\ln|x+1| + \\frac{6}{x+1} + C$$", practice: "\\frac{dx}{x^2(x-1)}", practiceAns: "-\\frac{1}{x} + \\ln|x-1| - \\ln|x| + C" },
        { name: "7.3. ∫ (x³+1) / (x³-x²) dx", integral: "\\frac{x^3+1}{x^3-x^2}\\,dx", answer: "x - \\ln|x| + \\frac{1}{x} + 2\\ln|x-1| + C", solution: "$$\\frac{x^3+1}{x^3-x^2} = 1 + \\frac{x^2+1}{x^2(x-1)} = 1 + \\frac{A}{x} + \\frac{B}{x^2} + \\frac{C}{x-1}$$ $$x^2+1 = Ax(x-1) + B(x-1) + Cx^2$$ $$x=0: \\; 1 = -B \\quad\\Rightarrow\\quad B = -1$$ $$x=1: \\; 2 = C \\quad\\Rightarrow\\quad C = 2$$ $$\\text{Коэф. при }x^2: \\; 1 = A+C \\quad\\Rightarrow\\quad A = -1$$ $$\\int\\left(1 - \\frac{1}{x} - \\frac{1}{x^2} + \\frac{2}{x-1}\\right)dx = x - \\ln|x| + \\frac{1}{x} + 2\\ln|x-1| + C$$", practice: "\\frac{x^2}{x^2-1}\\,dx", practiceAns: "x + \\frac{1}{2}\\ln|x-1| - \\frac{1}{2}\\ln|x+1| + C" },
        { name: "7.4. ∫ dx / (x(x²+1))", integral: "\\frac{dx}{x(x^2+1)}", answer: "\\ln|x| - \\frac{1}{2}\\ln(x^2+1) + C", solution: "$$\\frac{1}{x(x^2+1)} = \\frac{A}{x} + \\frac{Bx+C}{x^2+1}$$ $$1 = A(x^2+1) + (Bx+C)x$$ $$x=0: \\; 1 = A \\quad\\Rightarrow\\quad A = 1$$ $$\\text{Коэф. при }x^2: \\; 0 = A+B \\quad\\Rightarrow\\quad B = -1$$ $$\\text{Коэф. при }x: \\; 0 = C \\quad\\Rightarrow\\quad C = 0$$ $$\\int\\left(\\frac{1}{x} - \\frac{x}{x^2+1}\\right)dx = \\ln|x| - \\frac{1}{2}\\ln(x^2+1) + C$$", practice: "\\frac{dx}{x(x^2+4)}", practiceAns: "\\frac{1}{4}\\ln|x| - \\frac{1}{8}\\ln(x^2+4) + C" },
        { name: "7.5. ∫ x dx / (x³-1)", integral: "\\frac{x\\,dx}{x^3-1}", answer: "\\frac{1}{3}\\ln|x-1| - \\frac{1}{6}\\ln|x^2+x+1| + \\frac{1}{\\sqrt{3}}\\arctan\\left(\\frac{2x+1}{\\sqrt{3}}\\right) + C", solution: "$$x^3-1 = (x-1)(x^2+x+1)$$ $$\\frac{x}{x^3-1} = \\frac{A}{x-1} + \\frac{Bx+C}{x^2+x+1}$$ $$x=1: \\; 1 = 3A \\quad\\Rightarrow\\quad A = \\frac{1}{3}$$ $$\\text{Коэф. при }x^2: \\; 0 = A+B \\quad\\Rightarrow\\quad B = -\\frac{1}{3}$$ $$\\text{Свободный: } 0 = -A+C \\quad\\Rightarrow\\quad C = \\frac{1}{3}$$ $$\\frac{x}{x^3-1} = \\frac{1}{3(x-1)} - \\frac{x-1}{3(x^2+x+1)}$$ $$\\int \\frac{x-1}{x^2+x+1}\\,dx = \\frac{1}{2}\\ln(x^2+x+1) - \\frac{3}{2}\\int \\frac{dx}{(x+\\frac{1}{2})^2+\\frac{3}{4}}$$ $$= \\frac{1}{2}\\ln(x^2+x+1) - \\sqrt{3}\\arctan\\frac{2x+1}{\\sqrt{3}}$$ $$\\text{Итого: } \\frac{1}{3}\\ln|x-1| - \\frac{1}{6}\\ln|x^2+x+1| + \\frac{1}{\\sqrt{3}}\\arctan\\frac{2x+1}{\\sqrt{3}} + C$$", practice: "\\frac{dx}{x^3+1}", practiceAns: "\\frac{1}{3}\\ln|x+1| - \\frac{1}{6}\\ln|x^2-x+1| + \\frac{1}{\\sqrt{3}}\\arctan\\frac{2x-1}{\\sqrt{3}} + C" }
    ],

    section8: [
        { name: "8.1. ∫ sin³(2x)·cos⁴(2x) dx", integral: "\\sin^3(2x)\\cos^4(2x)\\,dx", answer: "-\\frac{1}{10}\\cos^5(2x) + \\frac{1}{14}\\cos^7(2x) + C", solution: "$$\\sin^3(2x)\\cos^4(2x) = \\sin^2(2x)\\cos^4(2x)\\cdot\\sin(2x) = (1-\\cos^2(2x))\\cos^4(2x)\\cdot\\sin(2x)$$ $$t = \\cos(2x), \\quad dt = -2\\sin(2x)\\,dx \\quad\\Rightarrow\\quad \\sin(2x)\\,dx = -\\frac{dt}{2}$$ $$\\int (1-t^2)t^4\\cdot\\left(-\\frac{dt}{2}\\right) = -\\frac{1}{2}\\int (t^4-t^6)\\,dt = -\\frac{1}{2}\\left(\\frac{t^5}{5} - \\frac{t^7}{7}\\right)$$ $$= -\\frac{1}{10}\\cos^5(2x) + \\frac{1}{14}\\cos^7(2x) + C$$", practice: "\\sin x\\cos^2 x\\,dx", practiceAns: "-\\frac{\\cos^3 x}{3} + C" },
        { name: "8.2. ∫ cos⁵x / √(sin x) dx", integral: "\\frac{\\cos^5 x}{\\sqrt{\\sin x}}\\,dx", answer: "\\frac{2}{3}\\sin^{3/2} x - \\frac{4}{7}\\sin^{7/2} x + \\frac{2}{11}\\sin^{11/2} x + C", solution: "$$\\cos^5 x = \\cos^4 x\\cdot\\cos x = (1-\\sin^2 x)^2\\cdot\\cos x$$ $$t = \\sin x, \\quad dt = \\cos x\\,dx$$ $$\\int \\frac{(1-t^2)^2}{\\sqrt{t}}\\,dt = \\int \\frac{1-2t^2+t^4}{t^{1/2}}\\,dt = \\int\\left(t^{-1/2} - 2t^{3/2} + t^{7/2}\\right)dt$$ $$= 2t^{1/2} - \\frac{4}{5}t^{5/2} + \\frac{2}{9}t^{9/2} = 2\\sqrt{\\sin x} - \\frac{4}{5}\\sin^{5/2} x + \\frac{2}{9}\\sin^{9/2} x + C$$", practice: "\\cos^3 x\\sqrt{\\sin x}\\,dx", practiceAns: "\\frac{2}{3}\\sin^{3/2} x - \\frac{2}{7}\\sin^{7/2} x + C" },
        { name: "8.3. ∫ sin²x·cos²x dx", integral: "\\sin^2 x\\cos^2 x\\,dx", answer: "\\frac{x}{8} - \\frac{\\sin(4x)}{32} + C", solution: "$$\\sin x\\cos x = \\frac{1}{2}\\sin 2x \\quad\\Rightarrow\\quad \\sin^2 x\\cos^2 x = \\frac{1}{4}\\sin^2 2x$$ $$\\sin^2 2x = \\frac{1-\\cos 4x}{2} \\quad\\Rightarrow\\quad \\sin^2 x\\cos^2 x = \\frac{1}{8}(1-\\cos 4x)$$ $$\\int \\frac{1}{8}(1-\\cos 4x)\\,dx = \\frac{x}{8} - \\frac{\\sin 4x}{32} + C$$", practice: "\\sin^2 x\\,dx", practiceAns: "\\frac{x}{2} - \\frac{\\sin 2x}{4} + C" },
        { name: "8.4. ∫ sin⁴(3x) dx", integral: "\\sin^4(3x)\\,dx", answer: "\\frac{3}{8}x - \\frac{1}{12}\\sin(6x) + \\frac{1}{96}\\sin(12x) + C", solution: "$$\\sin^4(3x) = \\left(\\frac{1-\\cos 6x}{2}\\right)^2 = \\frac{1}{4}(1 - 2\\cos 6x + \\cos^2 6x)$$ $$\\cos^2 6x = \\frac{1+\\cos 12x}{2}$$ $$\\sin^4(3x) = \\frac{1}{4}\\left(1 - 2\\cos 6x + \\frac{1}{2} + \\frac{1}{2}\\cos 12x\\right) = \\frac{3}{8} - \\frac{1}{2}\\cos 6x + \\frac{1}{8}\\cos 12x$$ $$\\int \\sin^4(3x)\\,dx = \\frac{3}{8}x - \\frac{1}{12}\\sin 6x + \\frac{1}{96}\\sin 12x + C$$", practice: "\\cos^4 x\\,dx", practiceAns: "\\frac{3}{8}x + \\frac{1}{4}\\sin 2x + \\frac{1}{32}\\sin 4x + C" },
        { name: "8.5. ∫ tg(4x) dx", integral: "\\tan(4x)\\,dx", answer: "-\\frac{1}{4}\\ln|\\cos(4x)| + C", solution: "$$\\tan(4x) = \\frac{\\sin(4x)}{\\cos(4x)}$$ $$t = \\cos(4x), \\quad dt = -4\\sin(4x)\\,dx \\quad\\Rightarrow\\quad \\sin(4x)\\,dx = -\\frac{dt}{4}$$ $$\\int \\frac{\\sin(4x)}{\\cos(4x)}\\,dx = -\\frac{1}{4}\\int \\frac{dt}{t} = -\\frac{1}{4}\\ln|t| = -\\frac{1}{4}\\ln|\\cos(4x)| + C$$", practice: "\\tan x\\,dx", practiceAns: "-\\ln|\\cos x| + C" },
        { name: "8.6. ∫ ctg⁴(5x) dx", integral: "\\cot^4(5x)\\,dx", answer: "-\\frac{1}{15}\\cot^3(5x) + \\frac{1}{5}\\cot(5x) + x + C", solution: "$$\\cot^4(5x) = \\cot^2(5x)\\cdot\\cot^2(5x) = \\cot^2(5x)(\\csc^2(5x)-1) = \\cot^2(5x)\\csc^2(5x) - \\cot^2(5x)$$ $$\\text{Первый: } t = \\cot(5x), \\; dt = -5\\csc^2(5x)\\,dx \\quad\\Rightarrow\\quad \\int \\cot^2(5x)\\csc^2(5x)\\,dx = -\\frac{1}{5}\\int t^2\\,dt = -\\frac{t^3}{15}$$ $$\\text{Второй: } \\int \\cot^2(5x)\\,dx = \\int (\\csc^2(5x)-1)\\,dx = -\\frac{1}{5}\\cot(5x) - x$$ $$\\text{Итого: } -\\frac{1}{15}\\cot^3(5x) + \\frac{1}{5}\\cot(5x) + x + C$$", practice: "\\tan^4 x\\,dx", practiceAns: "\\frac{1}{3}\\tan^3 x - \\tan x + x + C" },
        { name: "8.7. ∫ dx / (2+sin²x)", integral: "\\frac{dx}{2+\\sin^2 x}", answer: "\\frac{1}{\\sqrt{6}}\\arctan\\left(\\frac{\\sqrt{3}\\tan x}{\\sqrt{2}}\\right) + C", solution: "$$\\text{Делим на }\\cos^2 x: \\quad \\frac{dx}{2+\\sin^2 x} = \\frac{\\sec^2 x\\,dx}{2\\sec^2 x + \\tan^2 x} = \\frac{\\sec^2 x\\,dx}{2(1+\\tan^2 x)+\\tan^2 x} = \\frac{\\sec^2 x\\,dx}{2+3\\tan^2 x}$$ $$t = \\tan x, \\quad dt = \\sec^2 x\\,dx$$ $$\\int \\frac{dt}{2+3t^2} = \\frac{1}{3}\\int \\frac{dt}{t^2+\\frac{2}{3}} = \\frac{1}{3}\\cdot\\frac{1}{\\sqrt{2/3}}\\arctan\\frac{t}{\\sqrt{2/3}} = \\frac{1}{\\sqrt{6}}\\arctan\\frac{\\sqrt{3}\\tan x}{\\sqrt{2}} + C$$", practice: "\\frac{dx}{1+\\cos^2 x}", practiceAns: "\\frac{1}{\\sqrt{2}}\\arctan\\frac{\\tan x}{\\sqrt{2}} + C" },
        { name: "8.8. ∫ dx / (5-3cos x)", integral: "\\frac{dx}{5-3\\cos x}", answer: "\\frac{1}{2}\\arctan(2\\tan(x/2)) + C", solution: "$$t = \\tan\\frac{x}{2}, \\quad \\cos x = \\frac{1-t^2}{1+t^2}, \\quad dx = \\frac{2\\,dt}{1+t^2}$$ $$\\int \\frac{dx}{5-3\\cos x} = \\int \\frac{\\frac{2\\,dt}{1+t^2}}{5-3\\cdot\\frac{1-t^2}{1+t^2}} = \\int \\frac{2\\,dt}{5(1+t^2)-3(1-t^2)} = \\int \\frac{2\\,dt}{2+8t^2}$$ $$= \\int \\frac{dt}{1+4t^2} = \\frac{1}{2}\\arctan(2t) = \\frac{1}{2}\\arctan\\left(2\\tan\\frac{x}{2}\\right) + C$$", practice: "\\frac{dx}{2+\\cos x}", practiceAns: "\\frac{2}{\\sqrt{3}}\\arctan\\frac{\\tan(x/2)}{\\sqrt{3}} + C" },
        { name: "8.9. ∫ dx / (1+sin 2x)", integral: "\\frac{dx}{1+\\sin(2x)}", answer: "-\\frac{1}{\\tan x + 1} + C", solution: "$$1+\\sin 2x = (\\sin x + \\cos x)^2 = \\cos^2 x\\,(\\tan x + 1)^2$$ $$\\int \\frac{dx}{1+\\sin 2x} = \\int \\frac{dx}{\\cos^2 x\\,(\\tan x+1)^2} = \\int \\frac{\\sec^2 x\\,dx}{(\\tan x+1)^2}$$ $$t = \\tan x + 1, \\quad dt = \\sec^2 x\\,dx$$ $$\\int \\frac{dt}{t^2} = -\\frac{1}{t} = -\\frac{1}{\\tan x + 1} + C$$", practice: "\\frac{dx}{1+\\cos 2x}", practiceAns: "\\frac{1}{2}\\tan x + C" },
        { name: "8.10. ∫ cos(3x)·cos(5x) dx", integral: "\\cos(3x)\\cos(5x)\\,dx", answer: "\\frac{1}{16}\\sin(8x) + \\frac{1}{4}\\sin(2x) + C", solution: "$$\\cos A\\cos B = \\frac{1}{2}\\bigl[\\cos(A-B) + \\cos(A+B)\\bigr]$$ $$\\cos(3x)\\cos(5x) = \\frac{1}{2}\\bigl[\\cos(-2x) + \\cos(8x)\\bigr] = \\frac{1}{2}\\bigl[\\cos 2x + \\cos 8x\\bigr]$$ $$\\int \\frac{1}{2}(\\cos 2x + \\cos 8x)\\,dx = \\frac{1}{4}\\sin 2x + \\frac{1}{16}\\sin 8x + C$$", practice: "\\sin 4x\\cos 2x\\,dx", practiceAns: "-\\frac{1}{12}\\cos 6x - \\frac{1}{4}\\cos 2x + C" }
    ],

    section9: [
        { name: "9.1. ∫ √(25-x²) dx", integral: "\\sqrt{25-x^2}\\,dx", answer: "\\frac{25}{2}\\arcsin\\left(\\frac{x}{5}\\right) + \\frac{x}{2}\\sqrt{25-x^2} + C", solution: "$$x = 5\\sin t, \\quad dx = 5\\cos t\\,dt, \\quad \\sqrt{25-x^2} = 5\\cos t$$ $$\\int \\sqrt{25-x^2}\\,dx = \\int 5\\cos t \\cdot 5\\cos t\\,dt = 25\\int \\cos^2 t\\,dt = \\frac{25}{2}\\int (1+\\cos 2t)\\,dt$$ $$= \\frac{25}{2}\\left(t + \\frac{1}{2}\\sin 2t\\right) = \\frac{25}{2}t + \\frac{25}{2}\\sin t\\cos t$$ $$t = \\arcsin\\frac{x}{5}, \\quad \\sin t = \\frac{x}{5}, \\quad \\cos t = \\frac{\\sqrt{25-x^2}}{5}$$ $$= \\frac{25}{2}\\arcsin\\frac{x}{5} + \\frac{x}{2}\\sqrt{25-x^2} + C$$", practice: "\\sqrt{4-x^2}\\,dx", practiceAns: "2\\arcsin(x/2) + \\frac{x}{2}\\sqrt{4-x^2} + C" },
        { name: "9.2. ∫ √(9+x²) / x⁴ dx", integral: "\\frac{\\sqrt{9+x^2}}{x^4}\\,dx", answer: "-\\frac{(9+x^2)^{3/2}}{27x^3} + C", solution: "$$x = 3\\tan t, \\quad dx = 3\\sec^2 t\\,dt, \\quad \\sqrt{9+x^2} = 3\\sec t$$ $$\\int \\frac{3\\sec t}{81\\tan^4 t}\\cdot 3\\sec^2 t\\,dt = \\frac{1}{9}\\int \\frac{\\sec^3 t}{\\tan^4 t}\\,dt = \\frac{1}{9}\\int \\frac{1}{\\cos^3 t}\\cdot\\frac{\\cos^4 t}{\\sin^4 t}\\,dt = \\frac{1}{9}\\int \\frac{\\cos t}{\\sin^4 t}\\,dt$$ $$u = \\sin t, \\quad du = \\cos t\\,dt$$ $$\\frac{1}{9}\\int u^{-4}\\,du = \\frac{1}{9}\\cdot\\frac{u^{-3}}{-3} = -\\frac{1}{27\\sin^3 t}$$ $$\\tan t = \\frac{x}{3} \\quad\\Rightarrow\\quad \\sin t = \\frac{x}{\\sqrt{9+x^2}}$$ $$= -\\frac{(9+x^2)^{3/2}}{27x^3} + C$$", practice: "\\frac{dx}{x^2\\sqrt{x^2+1}}", practiceAns: "-\\frac{\\sqrt{x^2+1}}{x} + C" },
        { name: "9.3. ∫ dx / √((x²-1)³)", integral: "\\frac{dx}{\\sqrt{(x^2-1)^3}}", answer: "-\\frac{x}{\\sqrt{x^2-1}} + C", solution: "$$x = \\sec t, \\quad dx = \\sec t\\tan t\\,dt, \\quad \\sqrt{x^2-1} = \\tan t$$ $$\\int \\frac{\\sec t\\tan t\\,dt}{\\tan^3 t} = \\int \\frac{\\sec t}{\\tan^2 t}\\,dt = \\int \\frac{1/\\cos t}{\\sin^2 t/\\cos^2 t}\\,dt = \\int \\frac{\\cos t}{\\sin^2 t}\\,dt$$ $$u = \\sin t, \\quad du = \\cos t\\,dt$$ $$\\int u^{-2}\\,du = -\\frac{1}{u} = -\\frac{1}{\\sin t}$$ $$\\sec t = x \\quad\\Rightarrow\\quad \\cos t = \\frac{1}{x} \\quad\\Rightarrow\\quad \\sin t = \\frac{\\sqrt{x^2-1}}{x}$$ $$-\\frac{1}{\\sin t} = -\\frac{x}{\\sqrt{x^2-1}} + C$$", practice: "\\frac{dx}{\\sqrt{x^2-1}}", practiceAns: "\\ln\\left|x+\\sqrt{x^2-1}\\right| + C" }
    ]
};
