// integrals-data.js — РОВНО 135 ЗАДАЧ (из твоего исходного файла)
const INTEGRALS_DATA = {
    // ==================== РАЗДЕЛ 1: ТАБЛИЧНЫЕ ИНТЕГРАЛЫ (20 задач) ====================
    section1: [
        { name: "1.1 ∫ (3cos x - 3^x + 2√x) dx", integral: "(3\\cos x - 3^x + 2\\sqrt{x}) dx", answer: "3\\sin x - \\frac{3^x}{\\ln 3} + \\frac{4}{3}\\sqrt{x^3} + C", solution: "Интегрируем почленно: ∫3cos x dx = 3sin x; ∫3^x dx = 3^x/ln3; 2∫x^{1/2}dx = (4/3)√(x³).", practice: "(2\\sin x - 2^x + 3\\sqrt[3]{x}) dx", practiceAns: "-2\\cos x - \\frac{2^x}{\\ln 2} + \\frac{9}{4}\\sqrt[3]{x^4} + C" },
        { name: "1.2 ∫ ((2-x)/x)² dx", integral: "\\left(\\frac{2-x}{x}\\right)^2 dx", answer: "-\\frac{4}{x} - 4\\ln|x| + x + C", solution: "Раскрываем: (4 - 4x + x²)/x² = 4/x² - 4/x + 1. Интегрируем почленно.", practice: "\\left(\\frac{3-x}{x}\\right)^2 dx", practiceAns: "-\\frac{9}{x} - 6\\ln|x| + x + C" },
        { name: "1.3 ∫ (∛x² - ∜x)/√x dx", integral: "\\frac{\\sqrt[3]{x^2} - \\sqrt[4]{x}}{\\sqrt{x}} dx", answer: "\\frac{6}{7}x^{7/6} - \\frac{4}{3}x^{3/4} + C", solution: "Переводим в степени: x^{2/3-1/2}=x^{1/6}; x^{1/4-1/2}=x^{-1/4}.", practice: "\\frac{\\sqrt[3]{x} - \\sqrt[5]{x^2}}{\\sqrt[4]{x}} dx", practiceAns: "\\frac{12}{13}x^{13/12} - \\frac{20}{17}x^{17/20} + C" },
        { name: "1.4 ∫ (3·2^x - 2·3^x)/2^x dx", integral: "\\frac{3\\cdot2^x - 2\\cdot3^x}{2^x} dx", answer: "3x - 2\\cdot\\frac{(3/2)^x}{\\ln(3/2)} + C", solution: "Делим почленно: 3 - 2·(3/2)^x.", practice: "\\frac{4\\cdot3^x - 3\\cdot2^x}{3^x} dx", practiceAns: "4x - 3\\cdot\\frac{(2/3)^x}{\\ln(2/3)} + C" },
        { name: "1.5 ∫ (1+2x²)/(x²(1+x²)) dx", integral: "\\frac{1+2x^2}{x^2(1+x^2)} dx", answer: "-\\frac{1}{x} + \\arctan x + C", solution: "Разложение: (1+x²+x²)/(x²(1+x²)) = 1/x² + 1/(1+x²).", practice: "\\frac{1+3x^2}{x^2(1+x^2)} dx", practiceAns: "-\\frac{1}{x} + 2\\arctan x + C" },
        { name: "1.6 ∫ ctg² x dx", integral: "\\cot^2 x dx", answer: "-\\cot x - x + C", solution: "ctg²x = 1/sin²x - 1.", practice: "\\tan^2 x dx", practiceAns: "\\tan x - x + C" },
        { name: "1.7 ∫ dx/(cos2x + sin²x)", integral: "\\frac{dx}{\\cos 2x + \\sin^2 x}", answer: "\\tan x + C", solution: "cos2x = cos²x - sin²x → знаменатель = cos²x.", practice: "\\frac{dx}{\\cos 2x - \\cos^2 x}", practiceAns: "-\\cot x + C" },
        { name: "1.8 ∫ dx/√(9x²+1)", integral: "\\frac{dx}{\\sqrt{9x^2+1}}", answer: "\\frac{1}{3}\\ln|3x + \\sqrt{9x^2+1}| + C", solution: "∫dx/√(x²+a²) = ln|x+√(x²+a²)|.", practice: "\\frac{dx}{\\sqrt{4x^2+1}}", practiceAns: "\\frac{1}{2}\\ln|2x + \\sqrt{4x^2+1}| + C" },
        { name: "1.9 ∫ dx/√(3-5x²)", integral: "\\frac{dx}{\\sqrt{3-5x^2}}", answer: "\\frac{1}{\\sqrt{5}}\\arcsin\\left(x\\sqrt{\\frac{5}{3}}\\right) + C", solution: "∫dx/√(a²-x²) = arcsin(x/a).", practice: "\\frac{dx}{\\sqrt{2-3x^2}}", practiceAns: "\\frac{1}{\\sqrt{3}}\\arcsin\\left(x\\sqrt{\\frac{3}{2}}\\right) + C" },
        { name: "1.10 ∫ (√x - x³e^x + 2x²)/x³ dx", integral: "\\frac{\\sqrt{x} - x^3 e^x + 2x^2}{x^3} dx", answer: "-\\frac{2}{3x\\sqrt{x}} - e^x + 2\\ln|x| + C", solution: "Делим: x^{-5/2} - e^x + 2/x.", practice: "\\frac{\\sqrt[3]{x} - x^2 e^x + 3x}{x^2} dx", practiceAns: "\\frac{3}{5}x^{1/5} - e^x + 3\\ln|x| + C" },
        { name: "1.11 ∫ ∛(5x+2) dx", integral: "\\sqrt[3]{5x+2} dx", answer: "\\frac{3}{20}(5x+2)^{4/3} + C", solution: "∫(ax+b)^n dx = (1/a)·(ax+b)^{n+1}/(n+1).", practice: "\\sqrt[4]{3x-1} dx", practiceAns: "\\frac{4}{15}(3x-1)^{5/4} + C" },
        { name: "1.12 ∫ (2/(3x+4))² dx", integral: "\\left(\\frac{2}{3x+4}\\right)^2 dx", answer: "-\\frac{4}{3(3x+4)} + C", solution: "4∫(3x+4)^{-2}dx = 4·(1/3)·(3x+4)^{-1}/(-1).", practice: "\\left(\\frac{3}{2x-1}\\right)^2 dx", practiceAns: "-\\frac{9}{2(2x-1)} + C" },
        { name: "1.13 ∫ (3cos4x - 3^{2-x} + 4√(5-2x)) dx", integral: "(3\\cos 4x - 3^{2-x} + 4\\sqrt{5-2x}) dx", answer: "\\frac{3}{4}\\sin 4x + \\frac{3^{2-x}}{\\ln 3} - \\frac{4}{3}(5-2x)^{3/2} + C", solution: "∫3cos4x dx = (3/4)sin4x; ∫-3^{2-x}dx = 3^{2-x}/ln3.", practice: "(2\\sin 5x - 2^{3-x} + 3\\sqrt{4-3x}) dx", practiceAns: "-\\frac{2}{5}\\cos 5x + \\frac{2^{3-x}}{\\ln 2} - \\frac{2}{3}(4-3x)^{3/2} + C" },
        { name: "1.14 ∫ (1-x)²/(x(1+x²)) dx", integral: "\\frac{(1-x)^2}{x(1+x^2)} dx", answer: "\\ln|x| - 2\\arctan x + C", solution: "Раскрываем: (1-2x+x²)/(x(1+x²)) = 1/x - 2/(1+x²).", practice: "\\frac{(2-x)^2}{x(1+x^2)} dx", practiceAns: "4\\ln|x| - 4\\arctan x - \\frac{1}{2}\\ln(1+x^2) + C" },
        { name: "1.15 ∫ dx/√(9x²-5)", integral: "\\frac{dx}{\\sqrt{9x^2-5}}", answer: "\\frac{1}{3}\\ln|3x + \\sqrt{9x^2-5}| + C", solution: "∫dx/√(x²-a²) = ln|x+√(x²-a²)|.", practice: "\\frac{dx}{\\sqrt{16x^2-9}}", practiceAns: "\\frac{1}{4}\\ln|4x + \\sqrt{16x^2-9}| + C" },
        { name: "1.16 ∫ 2dx/(3-5x²)", integral: "\\frac{2dx}{3-5x^2}", answer: "\\frac{1}{\\sqrt{15}}\\ln\\left|\\frac{\\sqrt{3}+\\sqrt{5}x}{\\sqrt{3}-\\sqrt{5}x}\\right| + C", solution: "∫dx/(a²-x²) = (1/(2a))ln|(a+x)/(a-x)|.", practice: "\\frac{3dx}{4-7x^2}", practiceAns: "\\frac{3}{2\\sqrt{28}}\\ln\\left|\\frac{2+\\sqrt{7}x}{2-\\sqrt{7}x}\\right| + C" },
        { name: "1.17 ∫ (e^x+2)³ dx", integral: "(e^x+2)^3 dx", answer: "\\frac{1}{3}e^{3x} + 3e^{2x} + 12e^x + 8x + C", solution: "Раскрываем: e^{3x} + 6e^{2x} + 12e^x + 8.", practice: "(e^x+1)^3 dx", practiceAns: "\\frac{1}{3}e^{3x} + \\frac{3}{2}e^{2x} + 3e^x + x + C" },
        { name: "1.18 ∫ dx/(4-3x)", integral: "\\frac{dx}{4-3x}", answer: "-\\frac{1}{3}\\ln|4-3x| + C", solution: "∫dx/(ax+b) = (1/a)ln|ax+b|.", practice: "\\frac{dx}{5-2x}", practiceAns: "-\\frac{1}{2}\\ln|5-2x| + C" },
        { name: "1.19 ∫ x/(x+4) dx", integral: "\\frac{x}{x+4} dx", answer: "x - 4\\ln|x+4| + C", solution: "Выделяем целую часть: (x+4-4)/(x+4) = 1 - 4/(x+4).", practice: "\\frac{x}{x-2} dx", practiceAns: "x + 2\\ln|x-2| + C" },
        { name: "1.20 ∫ x/√(9x²-5) dx", integral: "\\frac{x}{\\sqrt{9x^2-5}} dx", answer: "\\frac{1}{9}\\sqrt{9x^2-5} + C", solution: "Замена t=9x²-5, dt=18x dx → x dx = dt/18.", practice: "\\frac{x}{\\sqrt{4x^2+1}} dx", practiceAns: "\\frac{1}{4}\\sqrt{4x^2+1} + C" },
            { name: "1.21 ∫ (√x + 1/√x) dx", integral: "(\\sqrt{x} + \\frac{1}{\\sqrt{x}}) dx", answer: "\\frac{2}{3}x^{3/2} + 2x^{1/2} + C", solution: "∫x^{1/2}dx = (2/3)x^{3/2}; ∫x^{-1/2}dx = 2x^{1/2}.", practice: "∫ (\\sqrt[3]{x} + 1/\\sqrt[3]{x}) dx", practiceAns: "\\frac{3}{4}x^{4/3} + \\frac{3}{2}x^{2/3} + C" },
        { name: "1.22 ∫ (e^{3x} + e^{-2x}) dx", integral: "(e^{3x} + e^{-2x}) dx", answer: "\\frac{1}{3}e^{3x} - \\frac{1}{2}e^{-2x} + C", solution: "∫e^{ax}dx = e^{ax}/a.", practice: "∫ (e^{4x} + e^{-3x}) dx", practiceAns: "\\frac{1}{4}e^{4x} - \\frac{1}{3}e^{-3x} + C" },
        { name: "1.23 ∫ (x^4 - 2x^3 + 1)/x² dx", integral: "\\frac{x^4 - 2x^3 + 1}{x^2} dx", answer: "\\frac{x^3}{3} - x^2 - \\frac{1}{x} + C", solution: "Делим: x² - 2x + x^{-2}.", practice: "∫ (x^4 - 3x^3 + 2)/x² dx", practiceAns: "\\frac{x^3}{3} - \\frac{3}{2}x^2 - \\frac{2}{x} + C" },
        { name: "1.24 ∫ tg²x·ctg x dx", integral: "\\tan^2 x \\cot x dx", answer: "\\ln|\\sin x| - \\ln|\\cos x| + C", solution: "tg²x·ctg x = tg x = sin x/cos x.", practice: "∫ ctg²x·tg x dx", practiceAns: "-\\ln|\\sin x| + \\ln|\\cos x| + C" },
        { name: "1.25 ∫ dx/(sin²x·cos²x)", integral: "\\frac{dx}{\\sin^2 x \\cos^2 x}", answer: "\\tan x - \\cot x + C", solution: "1/(sin²x cos²x) = 1/sin²x + 1/cos²x.", practice: "∫ dx/(sin²x·cos²x)", practiceAns: "\\tan x - \\cot x + C" },
        { name: "1.26 ∫ (3x² - 2x + 5) dx", integral: "(3x^2 - 2x + 5) dx", answer: "x^3 - x^2 + 5x + C", solution: "Почленное интегрирование.", practice: "∫ (4x³ - 3x² + 2x - 1) dx", practiceAns: "x^4 - x^3 + x^2 - x + C" },
        { name: "1.27 ∫ (a^{kx} + b^{-mx}) dx", integral: "(a^{kx} + b^{-mx}) dx", answer: "\\frac{a^{kx}}{k\\ln a} - \\frac{b^{-mx}}{m\\ln b} + C", solution: "∫a^{kx}dx = a^{kx}/(k ln a).", practice: "∫ (2^{3x} + 5^{-2x}) dx", practiceAns: "\\frac{2^{3x}}{3\\ln 2} - \\frac{5^{-2x}}{2\\ln 5} + C" }
    ],

    // ==================== РАЗДЕЛ 2: ЗАМЕНА ПЕРЕМЕННОЙ (16 задач) ====================
    section2: [
        { name: "2.1 ∫ 3cos(4x+2) dx", integral: "3\\cos(4x+2) dx", answer: "\\frac{3}{4}\\sin(4x+2) + C", solution: "dx = (1/4)d(4x+2).", practice: "2\\sin(3x-1) dx", practiceAns: "-\\frac{2}{3}\\cos(3x-1) + C" },
        { name: "2.2 ∫ (8-5x)^8 dx", integral: "(8-5x)^8 dx", answer: "-\\frac{(8-5x)^9}{45} + C", solution: "dx = -du/5, u=8-5x.", practice: "(3-2x)^5 dx", practiceAns: "-\\frac{(3-2x)^6}{12} + C" },
        { name: "2.3 ∫ x²·∛(x³-4) dx", integral: "x^2\\sqrt[3]{x^3-4} dx", answer: "\\frac{1}{4}(x^3-4)^{4/3} + C", solution: "t=x³-4, dt=3x²dx → x²dx = dt/3.", practice: "x^2\\sqrt[4]{x^3+2} dx", practiceAns: "\\frac{4}{15}(x^3+2)^{5/4} + C" },
        { name: "2.4 ∫ (sin x + 4)/cos²x dx", integral: "\\frac{\\sin x + 4}{\\cos^2 x} dx", answer: "\\frac{1}{\\cos x} + 4\\tan x + C", solution: "Разбиваем: ∫sin x/cos²x dx + 4∫dx/cos²x.", practice: "\\frac{\\cos x + 2}{\\sin^2 x} dx", practiceAns: "-\\frac{1}{\\sin x} - 2\\cot x + C" },
        { name: "2.5 ∫ √(ln x + 5)/x dx", integral: "\\frac{\\sqrt{\\ln x + 5}}{x} dx", answer: "\\frac{2}{3}(\\ln x + 5)^{3/2} + C", solution: "t=ln x+5, dt=dx/x.", practice: "\\frac{\\ln x}{x} dx", practiceAns: "\\frac{1}{2}(\\ln x)^2 + C" },
        { name: "2.6 ∫ e^{arccos 2x}/√(1-4x²) dx", integral: "\\frac{e^{\\arccos 2x}}{\\sqrt{1-4x^2}} dx", answer: "-\\frac{1}{2}e^{\\arccos 2x} + C", solution: "t=arccos 2x, dt = -2/√(1-4x²) dx.", practice: "\\frac{e^{\\arcsin 3x}}{\\sqrt{1-9x^2}} dx", practiceAns: "\\frac{1}{3}e^{\\arcsin 3x} + C" },
        { name: "2.7 ∫ dx/(1+√(x+2))", integral: "\\frac{dx}{1+\\sqrt{x+2}}", answer: "2\\sqrt{x+2} - 2\\ln(\\sqrt{x+2}+1) + C", solution: "t=√(x+2), x=t²-2, dx=2t dt.", practice: "\\frac{dx}{1+\\sqrt{x+3}}", practiceAns: "2\\sqrt{x+3} - 2\\ln(\\sqrt{x+3}+1) + C" },
        { name: "2.8 ∫ x² e^{-3x³} dx", integral: "x^2 e^{-3x^3} dx", answer: "-\\frac{1}{9}e^{-3x^3} + C", solution: "t=-3x³, dt=-9x²dx.", practice: "x e^{-x^2} dx", practiceAns: "-\\frac{1}{2}e^{-x^2} + C" },
        { name: "2.9 ∫ √(5x+2) dx", integral: "\\sqrt{5x+2} dx", answer: "\\frac{2}{15}(5x+2)^{3/2} + C", solution: "∫(5x+2)^{1/2}dx = (1/5)·(2/3)(5x+2)^{3/2}.", practice: "\\sqrt{3x-1} dx", practiceAns: "\\frac{2}{9}(3x-1)^{3/2} + C" },
        { name: "2.10 ∫ x√(5-3x²) dx", integral: "x\\sqrt{5-3x^2} dx", answer: "-\\frac{1}{9}(5-3x^2)^{3/2} + C", solution: "t=5-3x², dt=-6x dx.", practice: "x\\sqrt{4-x^2} dx", practiceAns: "-\\frac{1}{3}(4-x^2)^{3/2} + C" },
        { name: "2.11 ∫ (3x+2)/√(9-x²) dx", integral: "\\frac{3x+2}{\\sqrt{9-x^2}} dx", answer: "-3\\sqrt{9-x^2} + 2\\arcsin\\frac{x}{3} + C", solution: "Разбиваем: 3∫x/√(9-x²)dx + 2∫dx/√(9-x²).", practice: "\\frac{2x-1}{\\sqrt{4-x^2}} dx", practiceAns: "-2\\sqrt{4-x^2} - \\arcsin\\frac{x}{2} + C" },
        { name: "2.12 ∫ cos(3-e^x)·e^x dx", integral: "\\cos(3-e^x) e^x dx", answer: "-\\sin(3-e^x) + C", solution: "t=3-e^x, dt=-e^x dx.", practice: "\\sin(2-e^x) e^x dx", practiceAns: "\\cos(2-e^x) + C" },
        { name: "2.13 ∫ x/(1+x⁴) dx", integral: "\\frac{x}{1+x^4} dx", answer: "\\frac{1}{2}\\arctan(x^2) + C", solution: "t=x², dt=2x dx.", practice: "\\frac{x}{1+x^4} dx", practiceAns: "\\frac{1}{2}\\arctan(x^2) + C" },
        { name: "2.14 ∫ dx/(ln x·x)", integral: "\\frac{dx}{\\ln x \\cdot x}", answer: "\\ln|\\ln x| + C", solution: "t=ln x, dt=dx/x.", practice: "\\frac{dx}{x\\ln^2 x}", practiceAns: "-\\frac{1}{\\ln x} + C" },
        { name: "2.15 ∫ 2dx/(arctg(x/2)·(4+x²))", integral: "\\frac{2dx}{\\arctan(x/2) (4+x^2)}", answer: "\\ln|\\arctan(x/2)| + C", solution: "t=arctan(x/2), dt = 2dx/(4+x²).", practice: "\\frac{dx}{\\arcsin(x) \\sqrt{1-x^2}}", practiceAns: "\\ln|\\arcsin x| + C" },
        { name: "2.16 ∫ (1+e^{3x})⁵ e^{3x} dx", integral: "(1+e^{3x})^5 e^{3x} dx", answer: "\\frac{1}{18}(1+e^{3x})^6 + C", solution: "t=1+e^{3x}, dt=3e^{3x}dx.", practice: "(1+e^{2x})^4 e^{2x} dx", practiceAns: "\\frac{1}{10}(1+e^{2x})^5 + C" },
            { name: "2.17 ∫ dx/(5x+3)", integral: "\\frac{dx}{5x+3}", answer: "\\frac{1}{5}\\ln|5x+3| + C", solution: "∫dx/(ax+b) = (1/a)ln|ax+b|.", practice: "∫ dx/(3x+7)", practiceAns: "\\frac{1}{3}\\ln|3x+7| + C" },
        { name: "2.18 ∫ e^{4x-1} dx", integral: "e^{4x-1} dx", answer: "\\frac{1}{4}e^{4x-1} + C", solution: "∫e^{ax+b}dx = e^{ax+b}/a.", practice: "∫ e^{2x+3} dx", practiceAns: "\\frac{1}{2}e^{2x+3} + C" },
        { name: "2.19 ∫ sin(5x-π/3) dx", integral: "\\sin(5x-\\pi/3) dx", answer: "-\\frac{1}{5}\\cos(5x-\\pi/3) + C", solution: "∫sin(ax+b)dx = -cos(ax+b)/a.", practice: "∫ cos(3x+π/4) dx", practiceAns: "\\frac{1}{3}\\sin(3x+\\pi/4) + C" },
        { name: "2.20 ∫ dx/√(2x-1)", integral: "\\frac{dx}{\\sqrt{2x-1}}", answer: "\\sqrt{2x-1} + C", solution: "∫(ax+b)^{-1/2}dx = (2/a)√(ax+b).", practice: "∫ dx/√(3x+4)", practiceAns: "\\frac{2}{3}\\sqrt{3x+4} + C" },
        { name: "2.21 ∫ (3x-2)^4 dx", integral: "(3x-2)^4 dx", answer: "\\frac{(3x-2)^5}{15} + C", solution: "∫(ax+b)^n dx = (ax+b)^{n+1}/[a(n+1)].", practice: "∫ (2x+1)^3 dx", practiceAns: "\\frac{(2x+1)^4}{8} + C" },
        { name: "2.22 ∫ dx/√(5-2x)", integral: "\\frac{dx}{\\sqrt{5-2x}}", answer: "-\\sqrt{5-2x} + C", solution: "∫(b-ax)^{-1/2}dx = -2√(b-ax)/a.", practice: "∫ dx/√(7-3x)", practiceAns: "-\\frac{2}{3}\\sqrt{7-3x} + C" }
    ],

    // ==================== РАЗДЕЛ 3: ИНТЕГРИРОВАНИЕ ПО ЧАСТЯМ (10 задач) ====================
    section3: [
        { name: "3.1 ∫ (3-x)sin2x dx", integral: "(3-x)\\sin 2x dx", answer: "\\frac{x-3}{2}\\cos 2x - \\frac{1}{4}\\sin 2x + C", solution: "u=3-x, dv=sin2x dx → du=-dx, v=-cos2x/2.", practice: "∫ (2x+1)cos3x dx", practiceAns: "\\frac{2x+1}{3}\\sin 3x + \\frac{2}{9}\\cos 3x + C" },
        { name: "3.2 ∫ x² ln x dx", integral: "x^2 \\ln x dx", answer: "\\frac{x^3}{3}\\ln x - \\frac{x^3}{9} + C", solution: "u=ln x, dv=x²dx → du=dx/x, v=x³/3.", practice: "∫ x ln x dx", practiceAns: "\\frac{x^2}{2}\\ln x - \\frac{x^2}{4} + C" },
        { name: "3.3 ∫ arcsin 3x dx", integral: "\\arcsin 3x dx", answer: "x\\arcsin 3x + \\frac{1}{3}\\sqrt{1-9x^2} + C", solution: "u=arcsin3x, dv=dx → du=3dx/√(1-9x²), v=x.", practice: "∫ arccos 2x dx", practiceAns: "x\\arccos 2x - \\frac{1}{2}\\sqrt{1-4x^2} + C" },
        { name: "3.4 ∫ arctg x dx", integral: "\\arctan x dx", answer: "x\\arctan x - \\frac{1}{2}\\ln(1+x^2) + C", solution: "u=arctan x, dv=dx → du=dx/(1+x²), v=x.", practice: "∫ \\arctan 2x dx", practiceAns: "x\\arctan 2x - \\frac{1}{4}\\ln(1+4x^2) + C" },
        { name: "3.5 ∫ x² e^{-x} dx", integral: "x^2 e^{-x} dx", answer: "-(x^2+2x+2)e^{-x} + C", solution: "По частям дважды.", practice: "∫ x e^{-2x} dx", practiceAns: "-\\frac{2x+1}{4}e^{-2x} + C" },
        { name: "3.6 ∫ ln x dx", integral: "\\ln x dx", answer: "x\\ln x - x + C", solution: "u=ln x, dv=dx → du=dx/x, v=x.", practice: "∫ \\ln(2x) dx", practiceAns: "x\\ln(2x) - x + C" },
        { name: "3.7 ∫ x sin x dx", integral: "x \\sin x dx", answer: "\\sin x - x\\cos x + C", solution: "u=x, dv=sin x dx → du=dx, v=-cos x.", practice: "∫ x cos x dx", practiceAns: "x\\sin x + \\cos x + C" },
        { name: "3.8 ∫ e^x cos x dx", integral: "e^x \\cos x dx", answer: "\\frac{e^x(\\sin x + \\cos x)}{2} + C", solution: "Циклический интеграл.", practice: "∫ e^x \\sin x dx", practiceAns: "\\frac{e^x(\\sin x - \\cos x)}{2} + C" },
        { name: "3.9 ∫ x² ln(1+x) dx", integral: "x^2 \\ln(1+x) dx", answer: "\\frac{x^3}{3}\\ln(1+x) - \\frac{x^2}{6} + \\frac{x}{3} - \\frac{1}{3}\\ln(1+x) + C", solution: "u=ln(1+x), dv=x²dx → du=dx/(1+x), v=x³/3.", practice: "∫ x \\ln(1+x) dx", practiceAns: "\\frac{x^2-1}{2}\\ln(1+x) - \\frac{x^2}{4} + \\frac{x}{2} + C" },
        { name: "3.10 ∫ x·arctg x dx", integral: "x \\arctan x dx", answer: "\\frac{x^2+1}{2}\\arctan x - \\frac{x}{2} + C", solution: "u=arctan x, dv=x dx → du=dx/(1+x²), v=x²/2.", practice: "∫ x^2 \\arctan x dx", practiceAns: "\\frac{x^3}{3}\\arctan x - \\frac{x^2}{6} + \\frac{1}{6}\\ln(1+x^2) + C" },
            { name: "3.11 ∫ x cos x dx", integral: "x \\cos x dx", answer: "x\\sin x + \\cos x + C", solution: "u=x, dv=cos x dx → du=dx, v=sin x.", practice: "∫ x sin 2x dx", practiceAns: "-\\frac{x}{2}\\cos 2x + \\frac{1}{4}\\sin 2x + C" },
        { name: "3.12 ∫ x² e^{2x} dx", integral: "x^2 e^{2x} dx", answer: "\\frac{e^{2x}}{2}\\left(x^2 - x + \\frac{1}{2}\\right) + C", solution: "По частям дважды.", practice: "∫ x² e^{3x} dx", practiceAns: "\\frac{e^{3x}}{3}\\left(x^2 - \\frac{2x}{3} + \\frac{2}{9}\\right) + C" },
        { name: "3.13 ∫ ln(ax+b) dx", integral: "\\ln(ax+b) dx", answer: "\\frac{ax+b}{a}\\ln(ax+b) - x + C", solution: "u=ln(ax+b), dv=dx.", practice: "∫ ln(3x+1) dx", practiceAns: "\\frac{3x+1}{3}\\ln(3x+1) - x + C" },
        { name: "3.14 ∫ arcsin x dx", integral: "\\arcsin x dx", answer: "x\\arcsin x + \\sqrt{1-x^2} + C", solution: "u=arcsin x, dv=dx.", practice: "∫ arccos x dx", practiceAns: "x\\arccos x - \\sqrt{1-x^2} + C" },
        { name: "3.15 ∫ arctg(2x) dx", integral: "\\arctan(2x) dx", answer: "x\\arctan 2x - \\frac{1}{4}\\ln(1+4x^2) + C", solution: "u=arctan2x, dv=dx.", practice: "∫ arctg(3x) dx", practiceAns: "x\\arctan 3x - \\frac{1}{6}\\ln(1+9x^2) + C" },
            { name: "3.16 ∫ xⁿ ln x dx (общий вид)", integral: "x^n \\ln x dx", answer: "\\frac{x^{n+1}}{n+1}\\ln x - \\frac{x^{n+1}}{(n+1)^2} + C", solution: "u=ln x, dv=xⁿdx. При n≠-1.", practice: "∫ x⁴ ln x dx", practiceAns: "\\frac{x^5}{5}\\ln x - \\frac{x^5}{25} + C" },
        { name: "3.17 ∫ e^{ax} cos(bx) dx (общий вид)", integral: "e^{ax} \\cos(bx) dx", answer: "\\frac{e^{ax}(a\\cos(bx) + b\\sin(bx))}{a^2+b^2} + C", solution: "Циклический интеграл. Интегрируем по частям дважды, получаем уравнение.", practice: "∫ e^{2x} sin(3x) dx", practiceAns: "\\frac{e^{2x}(2\\sin 3x - 3\\cos 3x)}{13} + C" },
        { name: "3.18 ∫ x² e^{ax} dx (общий вид)", integral: "x^2 e^{ax} dx", answer: "\\frac{e^{ax}}{a}\\left(x^2 - \\frac{2x}{a} + \\frac{2}{a^2}\\right) + C", solution: "По частям дважды. u=x², dv=e^{ax}dx.", practice: "∫ x³ e^{2x} dx", practiceAns: "\\frac{e^{2x}}{2}\\left(x^3 - \\frac{3x^2}{2} + \\frac{3x}{2} - \\frac{3}{4}\\right) + C" },
        { name: "3.19 ∫ Pₙ(x) sin(ax) dx (общий вид)", integral: "P_n(x) \\sin(ax) dx", answer: "по частям n раз", solution: "Последовательно понижаем степень многочлена, пока не останется ∫ sin(ax) dx.", practice: "∫ (x³+2x) sin 2x dx", practiceAns: "по частям трижды" },
        { name: "3.20 ∫ Pₙ(x) e^{ax} dx (общий вид)", integral: "P_n(x) e^{ax} dx", answer: "\\frac{e^{ax}}{a}\\left(P_n(x) - \\frac{P_n'(x)}{a} + \\frac{P_n''(x)}{a^2} - ...\\right) + C", solution: "Метод неопределённых коэффициентов или последовательное интегрирование по частям.", practice: "∫ (x²+3x+1) e^{2x} dx", practiceAns: "\\frac{e^{2x}}{2}\\left(x^2+3x+1 - \\frac{2x+3}{2} + \\frac{2}{4}\\right) + C" }
    ],

    // ==================== РАЗДЕЛ 4: КВАДРАТНЫЙ ТРЁХЧЛЕН (8 задач) ====================
    section4: [
        { name: "4.1 ∫ dx/(x²+2x+5)", integral: "\\frac{dx}{x^2+2x+5}", answer: "\\frac{1}{2}\\arctan\\frac{x+1}{2} + C", solution: "Выделяем квадрат: (x+1)²+4.", practice: "∫ dx/(x²+4x+13)", practiceAns: "\\frac{1}{3}\\arctan\\frac{x+2}{3} + C" },
        { name: "4.2 ∫ dx/(x²-4x-5)", integral: "\\frac{dx}{x^2-4x-5}", answer: "\\frac{1}{6}\\ln\\left|\\frac{x-5}{x+1}\\right| + C", solution: "Выделяем квадрат: (x-2)²-9.", practice: "∫ dx/(x²-6x+5)", practiceAns: "\\frac{1}{4}\\ln\\left|\\frac{x-5}{x-1}\\right| + C" },
        { name: "4.3 ∫ dx/√(x²+4x+5)", integral: "\\frac{dx}{\\sqrt{x^2+4x+5}}", answer: "\\ln|x+2+\\sqrt{x^2+4x+5}| + C", solution: "Выделяем квадрат: (x+2)²+1.", practice: "∫ dx/√(x²+2x+2)", practiceAns: "\\ln|x+1+\\sqrt{x^2+2x+2}| + C" },
        { name: "4.4 ∫ dx/√(3-2x-x²)", integral: "\\frac{dx}{\\sqrt{3-2x-x^2}}", answer: "\\arcsin\\frac{x+1}{2} + C", solution: "3-2x-x² = 4-(x+1)².", practice: "∫ dx/√(5-4x-x²)", practiceAns: "\\arcsin\\frac{x+2}{3} + C" },
        { name: "4.5 ∫ dx/(9x²-6x+2)", integral: "\\frac{dx}{9x^2-6x+2}", answer: "\\frac{1}{3}\\arctan(3x-1) + C", solution: "9x²-6x+2 = (3x-1)²+1.", practice: "∫ dx/(4x²+4x+2)", practiceAns: "\\frac{1}{2}\\arctan(2x+1) + C" },
        { name: "4.6 ∫ dx/√(5-2x+x²)", integral: "\\frac{dx}{\\sqrt{5-2x+x^2}}", answer: "\\ln|x-1+\\sqrt{x^2-2x+5}| + C", solution: "x²-2x+5 = (x-1)²+4.", practice: "∫ dx/√(10-6x+x²)", practiceAns: "\\ln|x-3+\\sqrt{x^2-6x+10}| + C" },
        { name: "4.7 ∫ dx/√(10-6x+x²)", integral: "\\frac{dx}{\\sqrt{10-6x+x^2}}", answer: "\\ln|x-3+\\sqrt{x^2-6x+10}| + C", solution: "x²-6x+10 = (x-3)²+1.", practice: "∫ dx/√(x²-4x+8)", practiceAns: "\\ln|x-2+\\sqrt{x^2-4x+8}| + C" },
        { name: "4.8 ∫ dx/(x²-6x+12)", integral: "\\frac{dx}{x^2-6x+12}", answer: "\\frac{1}{\\sqrt{3}}\\arctan\\frac{x-3}{\\sqrt{3}} + C", solution: "x²-6x+12 = (x-3)²+3.", practice: "∫ dx/(x²-2x+5)", practiceAns: "\\frac{1}{2}\\arctan\\frac{x-1}{2} + C" },
            { name: "4.9 ∫ dx/(x²+4x+29)", integral: "\\frac{dx}{x^2+4x+29}", answer: "\\frac{1}{5}\\arctan\\frac{x+2}{5} + C", solution: "Выделяем квадрат: (x+2)²+25.", practice: "∫ dx/(x²-6x+25)", practiceAns: "\\frac{1}{4}\\arctan\\frac{x-3}{4} + C" },
        { name: "4.10 ∫ dx/√(x²-4x+8)", integral: "\\frac{dx}{\\sqrt{x^2-4x+8}}", answer: "\\ln|x-2+\\sqrt{x^2-4x+8}| + C", solution: "Выделяем квадрат: (x-2)²+4.", practice: "∫ dx/√(x²+6x+13)", practiceAns: "\\ln|x+3+\\sqrt{x^2+6x+13}| + C" },
        { name: "4.11 ∫ dx/√(5+4x-x²)", integral: "\\frac{dx}{\\sqrt{5+4x-x^2}}", answer: "\\arcsin\\frac{x-2}{3} + C", solution: "5+4x-x² = 9-(x-2)².", practice: "∫ dx/√(8+2x-x²)", practiceAns: "\\arcsin\\frac{x-1}{3} + C" },
        { name: "4.12 ∫ dx/(9x²+6x+2)", integral: "\\frac{dx}{9x^2+6x+2}", answer: "\\frac{1}{3}\\arctan(3x+1) + C", solution: "9x²+6x+2 = (3x+1)²+1.", practice: "∫ dx/(4x²+4x+5)", practiceAns: "\\frac{1}{2}\\arctan\\frac{2x+1}{2} + C" }
    ],

    // ==================== РАЗДЕЛ 5: ЛИНЕЙНЫЙ ЧЛЕН + ТРЁХЧЛЕН (6 задач) ====================
    section5: [
        { name: "5.1 ∫ (x+2)/(x²+2x+2) dx", integral: "\\frac{x+2}{x^2+2x+2} dx", answer: "\\frac{1}{2}\\ln(x^2+2x+2) + \\arctan(x+1) + C", solution: "Числитель = ½(2x+2) + 1.", practice: "∫ (x+1)/(x²+2x+2) dx", practiceAns: "\\frac{1}{2}\\ln(x^2+2x+2) + C" },
        { name: "5.2 ∫ (x-3)/√(3-2x-x²) dx", integral: "\\frac{x-3}{\\sqrt{3-2x-x^2}} dx", answer: "-\\sqrt{3-2x-x^2} - 2\\arcsin\\frac{x+1}{2} + C", solution: "Производная подкоренного = -2-2x = -2(x+1).", practice: "∫ (x+2)/√(5-4x-x²) dx", practiceAns: "-\\sqrt{5-4x-x^2} + \\arcsin\\frac{x+2}{3} + C" },
        { name: "5.3 ∫ (7x+3)/(4x²+8x+13) dx", integral: "\\frac{7x+3}{4x^2+8x+13} dx", answer: "\\frac{7}{8}\\ln(4x^2+8x+13) - \\frac{5}{4}\\arctan\\frac{2x+2}{3} + C", solution: "Производная знаменателя = 8x+8. 7x+3 = (7/8)(8x+8) - 4.", practice: "∫ (5x+1)/(x²+2x+5) dx", practiceAns: "\\frac{5}{2}\\ln(x^2+2x+5) - 4\\arctan\\frac{x+1}{2} + C" },
        { name: "5.4 ∫ (2x+5)/√(x²+6x+10) dx", integral: "\\frac{2x+5}{\\sqrt{x^2+6x+10}} dx", answer: "2\\sqrt{x^2+6x+10} - \\ln|x+3+\\sqrt{x^2+6x+10}| + C", solution: "Производная подкоренного = 2x+6. 2x+5 = (2x+6) - 1.", practice: "∫ (3x+4)/√(x²+4x+8) dx", practiceAns: "3\\sqrt{x^2+4x+8} - 2\\ln|x+2+\\sqrt{x^2+4x+8}| + C" },
        { name: "5.5 ∫ (1-x)/√(x²+4x+5) dx", integral: "\\frac{1-x}{\\sqrt{x^2+4x+5}} dx", answer: "-\\sqrt{x^2+4x+5} + 3\\ln|x+2+\\sqrt{x^2+4x+5}| + C", solution: "Производная подкоренного = 2x+4. 1-x = -½(2x+4) + 3.", practice: "∫ (2-x)/√(x²+2x+2) dx", practiceAns: "-\\sqrt{x^2+2x+2} + 3\\ln|x+1+\\sqrt{x^2+2x+2}| + C" },
        { name: "5.6 ∫ x/√(x²-10x+16) dx", integral: "\\frac{x}{\\sqrt{x^2-10x+16}} dx", answer: "\\sqrt{x^2-10x+16} + 5\\ln|x-5+\\sqrt{x^2-10x+16}| + C", solution: "Производная подкоренного = 2x-10. x = ½(2x-10) + 5.", practice: "∫ x/√(x²-6x+8) dx", practiceAns: "\\sqrt{x^2-6x+8} + 3\\ln|x-3+\\sqrt{x^2-6x+8}| + C" },
            { name: "5.7 ∫ (3x+1)/(x²+2x+5) dx", integral: "\\frac{3x+1}{x^2+2x+5} dx", answer: "\\frac{3}{2}\\ln(x^2+2x+5) - 2\\arctan\\frac{x+1}{2} + C", solution: "Производная знаменателя = 2x+2. 3x+1 = (3/2)(2x+2) - 2.", practice: "∫ (2x+3)/(x²+4x+13) dx", practiceAns: "\\ln(x^2+4x+13) - \\frac{1}{3}\\arctan\\frac{x+2}{3} + C" },
        { name: "5.8 ∫ (x+5)/√(x²+4x+5) dx", integral: "\\frac{x+5}{\\sqrt{x^2+4x+5}} dx", answer: "\\sqrt{x^2+4x+5} + 3\\ln|x+2+\\sqrt{x^2+4x+5}| + C", solution: "Производная подкоренного = 2x+4. x+5 = ½(2x+4) + 3.", practice: "∫ (2x+3)/√(x²+2x+2) dx", practiceAns: "2\\sqrt{x^2+2x+2} + \\ln|x+1+\\sqrt{x^2+2x+2}| + C" },
        { name: "5.9 ∫ (4x-3)/(x²-2x+5) dx", integral: "\\frac{4x-3}{x^2-2x+5} dx", answer: "2\\ln(x^2-2x+5) + \\frac{1}{2}\\arctan\\frac{x-1}{2} + C", solution: "Производная знаменателя = 2x-2. 4x-3 = 2(2x-2) + 1.", practice: "∫ (5x+2)/(x²+4x+20) dx", practiceAns: "\\frac{5}{2}\\ln(x^2+4x+20) - 4\\arctan\\frac{x+2}{4} + C" },
        { name: "5.10 ∫ (x-1)/√(x²-6x+10) dx", integral: "\\frac{x-1}{\\sqrt{x^2-6x+10}} dx", answer: "\\sqrt{x^2-6x+10} + 2\\ln|x-3+\\sqrt{x^2-6x+10}| + C", solution: "Производная подкоренного = 2x-6. x-1 = ½(2x-6) + 2.", practice: "∫ (x+2)/√(x²+2x+10) dx", practiceAns: "\\sqrt{x^2+2x+10} + \\ln|x+1+\\sqrt{x^2+2x+10}| + C" }
    ],

    // ==================== РАЗДЕЛ 6: ТИП dx/(x√(...)) (5 задач) ====================
    section6: [
        { name: "6.1 ∫ dx/(x√(2+2x-x²))", integral: "\\frac{dx}{x\\sqrt{2+2x-x^2}}", answer: "-\\frac{1}{\\sqrt{3}}\\ln\\left|\\frac{\\sqrt{3}+\\sqrt{2+2x-x^2}}{x}\\right| + C", solution: "Замена t=1/x → dx = -dt/t².", practice: "∫ dx/(x√(1+2x-x²))", practiceAns: "-\\frac{1}{\\sqrt{2}}\\ln\\left|\\frac{\\sqrt{2}+\\sqrt{1+2x-x^2}}{x}\\right| + C" },
        { name: "6.2 ∫ dx/(x√(x²-1))", integral: "\\frac{dx}{x\\sqrt{x^2-1}}", answer: "\\operatorname{arcsec}|x| + C", solution: "Табличный интеграл.", practice: "∫ dx/(x√(x²-4))", practiceAns: "\\frac{1}{2}\\operatorname{arcsec}\\frac{x}{2} + C" },
        { name: "6.3 ∫ dx/(x√(4-x²))", integral: "\\frac{dx}{x\\sqrt{4-x^2}}", answer: "-\\frac{1}{2}\\ln\\left|\\frac{2+\\sqrt{4-x^2}}{x}\\right| + C", solution: "Замена x=2sin t.", practice: "∫ dx/(x√(9-x²))", practiceAns: "-\\frac{1}{3}\\ln\\left|\\frac{3+\\sqrt{9-x^2}}{x}\\right| + C" },
        { name: "6.4 ∫ dx/(x√(x²+4))", integral: "\\frac{dx}{x\\sqrt{x^2+4}}", answer: "-\\frac{1}{2}\\ln\\left|\\frac{2+\\sqrt{x^2+4}}{x}\\right| + C", solution: "Замена x=2tg t.", practice: "∫ dx/(x√(x²+1))", practiceAns: "-\\ln\\left|\\frac{1+\\sqrt{x^2+1}}{x}\\right| + C" },
        { name: "6.5 ∫ dx/(x√(x²+2x+2))", integral: "\\frac{dx}{x\\sqrt{x^2+2x+2}}", answer: "-\\ln\\left|\\frac{1+\\sqrt{x^2+2x+2}}{x}\\right| + C", solution: "Замена t=1/x.", practice: "∫ dx/(x√(x²+4x+5))", practiceAns: "-\\ln\\left|\\frac{2+\\sqrt{x^2+4x+5}}{x}\\right| + C" },
            { name: "6.6 ∫ dx/(x√(x²+4x+5))", integral: "\\frac{dx}{x\\sqrt{x^2+4x+5}}", answer: "-\\ln\\left|\\frac{2+\\sqrt{x^2+4x+5}}{x}\\right| + C", solution: "Замена t=1/x.", practice: "∫ dx/(x√(x²+2x+2))", practiceAns: "-\\ln\\left|\\frac{1+\\sqrt{x^2+2x+2}}{x}\\right| + C" },
        { name: "6.7 ∫ dx/(x√(x²+2x+2))", integral: "\\frac{dx}{x\\sqrt{x^2+2x+2}}", answer: "-\\ln\\left|\\frac{1+\\sqrt{x^2+2x+2}}{x}\\right| + C", solution: "Замена t=1/x.", practice: "∫ dx/(x√(x²+6x+10))", practiceAns: "-\\ln\\left|\\frac{3+\\sqrt{x^2+6x+10}}{x}\\right| + C" },
        { name: "6.8 ∫ dx/(x√(x²-2x+2))", integral: "\\frac{dx}{x\\sqrt{x^2-2x+2}}", answer: "-\\ln\\left|\\frac{1+\\sqrt{x^2-2x+2}}{x}\\right| + C", solution: "Замена t=1/x.", practice: "∫ dx/(x√(x²-4x+8))", practiceAns: "-\\ln\\left|\\frac{2+\\sqrt{x^2-4x+8}}{x}\\right| + C" }
    ],

    // ==================== РАЗДЕЛ 7: ДРОБНО-РАЦИОНАЛЬНЫЕ (6 задач) ====================
    section7: [
        { name: "7.1 ∫ dx/(x(x+2))", integral: "\\frac{dx}{x(x+2)}", answer: "\\frac{1}{2}\\ln\\left|\\frac{x}{x+2}\\right| + C", solution: "Разложение: A/x + B/(x+2).", practice: "∫ dx/(x(x+3))", practiceAns: "\\frac{1}{3}\\ln\\left|\\frac{x}{x+3}\\right| + C" },
        { name: "7.2 ∫ (x+1)/((x-1)(x+2)) dx", integral: "\\frac{x+1}{(x-1)(x+2)} dx", answer: "\\frac{2}{3}\\ln|x-1| + \\frac{1}{3}\\ln|x+2| + C", solution: "Разложение: A/(x-1) + B/(x+2).", practice: "∫ (x+2)/((x-1)(x+3)) dx", practiceAns: "\\frac{3}{4}\\ln|x-1| + \\frac{1}{4}\\ln|x+3| + C" },
        { name: "7.3 ∫ dx/(x(x²+1))", integral: "\\frac{dx}{x(x^2+1)}", answer: "\\ln|x| - \\frac{1}{2}\\ln(x^2+1) + C", solution: "Разложение: A/x + (Bx+C)/(x²+1).", practice: "∫ dx/(x(x²+4))", practiceAns: "\\frac{1}{4}\\ln|x| - \\frac{1}{8}\\ln(x^2+4) + C" },
        { name: "7.4 ∫ (x³+1)/(x³-x²) dx", integral: "\\frac{x^3+1}{x^3-x^2} dx", answer: "x + \\ln|x-1| - \\frac{1}{x} + C", solution: "Делим: 1 + (x²+1)/(x²(x-1)).", practice: "∫ (x²+1)/(x²(x-1)) dx", practiceAns: "\\ln|x-1| - \\frac{1}{x} + C" },
        { name: "7.5 ∫ (x²+9)/((x-1)(x²-4)) dx", integral: "\\frac{x^2+9}{(x-1)(x^2-4)} dx", answer: "-\\frac{10}{3}\\ln|x-1| + \\frac{13}{6}\\ln|x-2| + \\frac{5}{2}\\ln|x+2| + C", solution: "x²-4 = (x-2)(x+2).", practice: "∫ (x²+5)/((x+1)(x²-1)) dx", practiceAns: "-\\frac{3}{2}\\ln|x+1| + \\frac{1}{2}\\ln|x-1| + \\frac{5}{2}\\ln|x+2| + C" },
        { name: "7.6 ∫ (1+4x²)/(x(x²+2x+1)) dx", integral: "\\frac{1+4x^2}{x(x^2+2x+1)} dx", answer: "\\ln|x| + 3\\ln|x+1| - \\frac{3}{x+1} + C", solution: "x²+2x+1 = (x+1)². Разложение: A/x + B/(x+1) + D/(x+1)².", practice: "∫ (1+2x²)/(x(x+1)²) dx", practiceAns: "\\ln|x| + \\ln|x+1| - \\frac{1}{x+1} + C" },
            { name: "7.7 ∫ (x+2)/(x²+3x+2) dx", integral: "\\frac{x+2}{x^2+3x+2} dx", answer: "\\ln|x+1| + C", solution: "x²+3x+2 = (x+1)(x+2). (x+2) сокращается.", practice: "∫ (x+3)/(x²+5x+6) dx", practiceAns: "\\ln|x+2| + C" },
        { name: "7.8 ∫ (2x+1)/(x²+x+1) dx", integral: "\\frac{2x+1}{x^2+x+1} dx", answer: "\\ln(x^2+x+1) + \\frac{2}{\\sqrt{3}}\\arctan\\frac{2x+1}{\\sqrt{3}} + C", solution: "Производная знаменателя = 2x+1.", practice: "∫ (3x+2)/(x²+2x+3) dx", practiceAns: "\\frac{3}{2}\\ln(x^2+2x+3) - \\frac{1}{\\sqrt{2}}\\arctan\\frac{x+1}{\\sqrt{2}} + C" },
        { name: "7.9 ∫ dx/((x-1)(x-2)(x-3))", integral: "\\frac{dx}{(x-1)(x-2)(x-3)}", answer: "\\frac{1}{2}\\ln|x-1| - \\ln|x-2| + \\frac{1}{2}\\ln|x-3| + C", solution: "Разложение на A/(x-1) + B/(x-2) + C/(x-3).", practice: "∫ dx/((x+1)(x+2)(x+3))", practiceAns: "\\frac{1}{2}\\ln|x+1| - \\ln|x+2| + \\frac{1}{2}\\ln|x+3| + C" },
        { name: "7.10 ∫ (2x²+3)/((x-1)(x²+1)) dx", integral: "\\frac{2x^2+3}{(x-1)(x^2+1)} dx", answer: "\\frac{5}{2}\\ln|x-1| + \\frac{1}{2}\\ln(x^2+1) - \\arctan x + C", solution: "Разложение: A/(x-1) + (Bx+C)/(x²+1).", practice: "∫ (3x²+1)/((x-2)(x²+4)) dx", practiceAns: "\\frac{13}{8}\\ln|x-2| + \\frac{1}{8}\\ln(x^2+4) - \\frac{1}{4}\\arctan\\frac{x}{2} + C" }
    ],

    // ==================== РАЗДЕЛ 8: ТРИГОНОМЕТРИЧЕСКИЕ (10 задач) ====================
    section8: [
        { name: "8.1 ∫ sin³2x·cos⁴2x dx", integral: "\\sin^3 2x \\cos^4 2x dx", answer: "\\frac{\\cos^7 2x}{14} - \\frac{\\cos^5 2x}{10} + C", solution: "Нечётная степень синуса → u=cos2x.", practice: "∫ sin³x·cos²x dx", practiceAns: "\\frac{\\cos^5 x}{5} - \\frac{\\cos^3 x}{3} + C" },
        { name: "8.2 ∫ cos⁵x/√(sin x) dx", integral: "\\frac{\\cos^5 x}{\\sqrt{\\sin x}} dx", answer: "2\\sqrt{\\sin x} - \\frac{4}{5}(\\sin x)^{5/2} + \\frac{2}{9}(\\sin x)^{9/2} + C", solution: "cos⁵x = (1-sin²x)²·cos x.", practice: "∫ sin³x·√(cos x) dx", practiceAns: "-2(\\cos x)^{3/2} + \\frac{2}{7}(\\cos x)^{7/2} + C" },
        { name: "8.3 ∫ sin²x·cos²x dx", integral: "\\sin^2 x \\cos^2 x dx", answer: "\\frac{x}{8} - \\frac{\\sin 4x}{32} + C", solution: "sin²x·cos²x = (1/4)sin²2x = (1/8)(1-cos4x).", practice: "∫ sin²x·cos⁴x dx", practiceAns: "\\frac{x}{16} - \\frac{\\sin 4x}{64} + \\frac{\\sin^3 2x}{48} + C" },
        { name: "8.4 ∫ sin⁴3x dx", integral: "\\sin^4 3x dx", answer: "\\frac{3x}{8} - \\frac{\\sin 6x}{12} + \\frac{\\sin 12x}{96} + C", solution: "sin⁴θ = (3/8) - (1/2)cos2θ + (1/8)cos4θ.", practice: "∫ cos⁴2x dx", practiceAns: "\\frac{3x}{8} + \\frac{\\sin 4x}{8} + \\frac{\\sin 8x}{64} + C" },
        { name: "8.5 ∫ tg 4x dx", integral: "\\tan 4x dx", answer: "-\\frac{1}{4}\\ln|\\cos 4x| + C", solution: "∫tg u du = -ln|cos u|.", practice: "∫ ctg 5x dx", practiceAns: "\\frac{1}{5}\\ln|\\sin 5x| + C" },
        { name: "8.6 ∫ ctg⁴5x dx", integral: "\\cot^4 5x dx", answer: "-\\frac{1}{5}\\cot^3 5x + \\frac{1}{5}\\cot 5x + x + C", solution: "ctg⁴u = ctg²u·(csc²u-1) = ctg²u·csc²u - ctg²u.", practice: "∫ tg³2x dx", practiceAns: "\\frac{1}{4}\\tan^2 2x - \\frac{1}{2}\\ln|\\cos 2x| + C" },
        { name: "8.7 ∫ dx/(2+sin²x)", integral: "\\frac{dx}{2+\\sin^2 x}", answer: "\\frac{1}{\\sqrt{6}}\\arctan\\left(\\sqrt{\\frac{3}{2}}\\tan x\\right) + C", solution: "Делим на cos²x: ∫dtgx/(2+tg²x).", practice: "∫ dx/(1+sin²x)", practiceAns: "\\frac{1}{\\sqrt{2}}\\arctan(\\sqrt{2}\\tan x) + C" },
        { name: "8.8 ∫ dx/(5-3cos x)", integral: "\\frac{dx}{5-3\\cos x}", answer: "\\frac{1}{2}\\arctan\\left(2\\tan\\frac{x}{2}\\right) + C", solution: "Универсальная подстановка t=tg(x/2).", practice: "∫ dx/(3-2cos x)", practiceAns: "\\frac{2}{\\sqrt{5}}\\arctan\\left(\\sqrt{5}\\tan\\frac{x}{2}\\right) + C" },
        { name: "8.9 ∫ cos3x·cos5x dx", integral: "\\cos 3x \\cos 5x dx", answer: "\\frac{1}{4}\\sin 2x + \\frac{1}{16}\\sin 8x + C", solution: "cosA·cosB = ½[cos(A-B)+cos(A+B)].", practice: "∫ sin4x·cos6x dx", practiceAns: "\\frac{1}{4}\\cos 2x - \\frac{1}{20}\\cos 10x + C" },
        { name: "8.10 ∫ sin3x·cos7x dx", integral: "\\sin 3x \\cos 7x dx", answer: "-\\frac{1}{8}\\cos 4x + \\frac{1}{20}\\cos 10x + C", solution: "sinA·cosB = ½[sin(A+B)+sin(A-B)].", practice: "∫ sin5x·sin3x dx", practiceAns: "\\frac{1}{4}\\sin 2x - \\frac{1}{16}\\sin 8x + C" },
        { name: "8.11 ∫ sin²x dx", integral: "\\sin^2 x dx", answer: "\\frac{x}{2} - \\frac{\\sin 2x}{4} + C", solution: "sin²x = (1-cos2x)/2.", practice: "∫ cos²x dx", practiceAns: "\\frac{x}{2} + \\frac{\\sin 2x}{4} + C" },
        { name: "8.12 ∫ sin³x dx", integral: "\\sin^3 x dx", answer: "-\\cos x + \\frac{1}{3}\\cos^3 x + C", solution: "sin³x = (1-cos²x)sin x.", practice: "∫ cos³x dx", practiceAns: "\\sin x - \\frac{1}{3}\\sin^3 x + C" },
        { name: "8.13 ∫ dx/(1+sin x)", integral: "\\frac{dx}{1+\\sin x}", answer: "-\\tan\\left(\\frac{x}{2} - \\frac{\\pi}{4}\\right) + C", solution: "Универсальная подстановка t=tg(x/2) или умножение на (1-sin x).", practice: "∫ dx/(1+cos x)", practiceAns: "\\tan\\frac{x}{2} + C" },
        { name: "8.14 ∫ dx/(sin x cos x)", integral: "\\frac{dx}{\\sin x \\cos x}", answer: "\\ln|\\tan x| + C", solution: "1/(sin x cos x) = 2/sin 2x.", practice: "∫ dx/(sin 2x)", practiceAns: "\\frac{1}{2}\\ln|\\tan x| + C" },
        { name: "8.15 ∫ dx/(a² sin²x + b² cos²x)", integral: "\\frac{dx}{a^2\\sin^2 x + b^2\\cos^2 x}", answer: "\\frac{1}{ab}\\arctan\\left(\\frac{a\\tan x}{b}\\right) + C", solution: "Делим на cos²x: ∫dtgx/(a² tg²x + b²).", practice: "∫ dx/(4\\sin^2 x + 9\\cos^2 x)", practiceAns: "\\frac{1}{6}\\arctan\\left(\\frac{2\\tan x}{3}\\right) + C" },
        { name: "8.16 ∫ dx/sin x", integral: "\\frac{dx}{\\sin x}", answer: "\\ln\\left|\\tan\\frac{x}{2}\\right| + C", solution: "Универсальная подстановка t=tg(x/2).", practice: "∫ dx/cos x", practiceAns: "\\ln\\left|\\tan\\left(\\frac{x}{2}+\\frac{\\pi}{4}\\right)\\right| + C" },
        { name: "8.17 ∫ dx/(1+sin x)", integral: "\\frac{dx}{1+\\sin x}", answer: "-\\tan\\left(\\frac{x}{2}-\\frac{\\pi}{4}\\right) + C", solution: "Умножаем на (1-sin x) или универсальная подстановка.", practice: "∫ dx/(1+cos x)", practiceAns: "\\tan\\frac{x}{2} + C" },
        { name: "8.18 ∫ dx/(sin x cos x)", integral: "\\frac{dx}{\\sin x \\cos x}", answer: "\\ln|\\tan x| + C", solution: "1/(sin x cos x) = 2/sin 2x.", practice: "∫ dx/(sin 2x)", practiceAns: "\\frac{1}{2}\\ln|\\tan x| + C" }
    ],

    // ==================== РАЗДЕЛ 9: ТРИГОНОМЕТРИЧЕСКАЯ ЗАМЕНА (6 задач) ====================
    section9: [
        { name: "9.1 ∫ √((4-x²)³)/x⁶ dx", integral: "\\frac{\\sqrt{(4-x^2)^3}}{x^6} dx", answer: "-\\frac{(4-x^2)^{5/2}}{20x^5} + C", solution: "x=2sin t.", practice: "∫ √((9-x²)³)/x⁵ dx", practiceAns: "-\\frac{(9-x^2)^{5/2}}{45x^4} + C" },
        { name: "9.2 ∫ √(9+x²)/x⁴ dx", integral: "\\frac{\\sqrt{9+x^2}}{x^4} dx", answer: "-\\frac{(9+x^2)^{3/2}}{27x^3} + C", solution: "x=3tg t.", practice: "∫ √(4+x²)/x³ dx", practiceAns: "-\\frac{\\sqrt{4+x^2}}{2x^2} + \\frac{1}{2}\\ln\\left|\\frac{\\sqrt{4+x^2}-2}{x}\\right| + C" },
        { name: "9.3 ∫ dx/√((x²-1)³)", integral: "\\frac{dx}{\\sqrt{(x^2-1)^3}}", answer: "-\\frac{x}{\\sqrt{x^2-1}} + C", solution: "x=sec t.", practice: "∫ dx/√((x²-4)³)", practiceAns: "-\\frac{x}{4\\sqrt{x^2-4}} + C" },
        { name: "9.4 ∫ √(25-x²) dx", integral: "\\sqrt{25-x^2} dx", answer: "\\frac{25}{2}\\arcsin\\frac{x}{5} + \\frac{x\\sqrt{25-x^2}}{2} + C", solution: "x=5sin t.", practice: "∫ √(9-x²) dx", practiceAns: "\\frac{9}{2}\\arcsin\\frac{x}{3} + \\frac{x\\sqrt{9-x^2}}{2} + C" },
        { name: "9.5 ∫ x³/√(x²+16) dx", integral: "\\frac{x^3}{\\sqrt{x^2+16}} dx", answer: "\\frac{(x^2+16)^{3/2}}{3} - 16\\sqrt{x^2+16} + C", solution: "Замена u=x²+16.", practice: "∫ x/√(x²+9) dx", practiceAns: "\\sqrt{x^2+9} + C" },
        { name: "9.6 ∫ √(x²-4)/x dx", integral: "\\frac{\\sqrt{x^2-4}}{x} dx", answer: "\\sqrt{x^2-4} - 2\\operatorname{arcsec}\\frac{x}{2} + C", solution: "x=2sec t.", practice: "∫ √(x²-9)/x dx", practiceAns: "\\sqrt{x^2-9} - 3\\operatorname{arcsec}\\frac{x}{3} + C" },
            { name: "9.7 ∫ √(x²+4)/x dx", integral: "\\frac{\\sqrt{x^2+4}}{x} dx", answer: "\\sqrt{x^2+4} - 2\\ln\\left|\\frac{2+\\sqrt{x^2+4}}{x}\\right| + C", solution: "x=2tg t.", practice: "∫ √(x²+9)/x dx", practiceAns: "\\sqrt{x^2+9} - 3\\ln\\left|\\frac{3+\\sqrt{x^2+9}}{x}\\right| + C" },
        { name: "9.8 ∫ dx/(x²√(x²-4))", integral: "\\frac{dx}{x^2\\sqrt{x^2-4}}", answer: "\\frac{\\sqrt{x^2-4}}{4x} + C", solution: "x=2sec t.", practice: "∫ dx/(x²√(x²-9))", practiceAns: "\\frac{\\sqrt{x^2-9}}{9x} + C" },
        { name: "9.9 ∫ dx/((x²+1)√(x²-1))", integral: "\\frac{dx}{(x^2+1)\\sqrt{x^2-1}}", answer: "\\frac{1}{\\sqrt{2}}\\arctan\\frac{\\sqrt{x^2-1}}{\\sqrt{2}x} + C", solution: "x=sec t.", practice: "∫ dx/((x²+4)√(x²-1))", practiceAns: "\\frac{1}{\\sqrt{5}}\\arctan\\frac{\\sqrt{x^2-1}}{\\sqrt{5}x} + C" },
        { name: "9.10 ∫ √(x²-2x+2)/x dx", integral: "\\frac{\\sqrt{x^2-2x+2}}{x} dx", answer: "\\sqrt{x^2-2x+2} + \\ln|x-1+\\sqrt{x^2-2x+2}| - \\ln|x| + C", solution: "Замена t=√(x²-2x+2).", practice: "∫ √(x²+2x+2)/x dx", practiceAns: "\\sqrt{x^2+2x+2} + \\ln|x+1+\\sqrt{x^2+2x+2}| - \\ln|x| + C" },
            { name: "9.11 ∫ √(x²+ax+b) dx (общий вид)", integral: "\\sqrt{x^2+ax+b} dx", answer: "\\frac{2x+a}{4}\\sqrt{x^2+ax+b} + \\frac{4b-a^2}{8}\\ln\\left|x+\\frac{a}{2}+\\sqrt{x^2+ax+b}\\right| + C", solution: "Выделяем полный квадрат и используем табличную формулу ∫√(t²±k²)dt.", practice: "∫ √(x²+4x+5) dx", practiceAns: "\\frac{x+2}{2}\\sqrt{x^2+4x+5} + \\frac{1}{2}\\ln|x+2+\\sqrt{x^2+4x+5}| + C" },
        { name: "9.12 ∫ dx/√(x²+ax+b) (общий вид)", integral: "\\frac{dx}{\\sqrt{x^2+ax+b}}", answer: "\\ln\\left|x+\\frac{a}{2}+\\sqrt{x^2+ax+b}\\right| + C", solution: "Выделяем полный квадрат и используем табличную формулу ∫dt/√(t²±k²).", practice: "∫ dx/√(x²+4x+5)", practiceAns: "\\ln|x+2+\\sqrt{x^2+4x+5}| + C" },
        { name: "9.13 ∫ dx/(x²+ax+b) (общий вид)", integral: "\\frac{dx}{x^2+ax+b}", answer: "\\frac{2}{\\sqrt{4b-a^2}}\\arctan\\frac{2x+a}{\\sqrt{4b-a^2}} + C", solution: "Выделяем полный квадрат.", practice: "∫ dx/(x²+4x+13)", practiceAns: "\\frac{1}{3}\\arctan\\frac{x+2}{3} + C" },
        { name: "9.14 ∫ dx/(x²+ax-b) (общий вид, a²+4b>0)", integral: "\\frac{dx}{x^2+ax-b}", answer: "\\frac{1}{\\sqrt{a^2+4b}}\\ln\\left|\\frac{2x+a-\\sqrt{a^2+4b}}{2x+a+\\sqrt{a^2+4b}}\\right| + C", solution: "Выделяем полный квадрат и используем ∫dt/(t²-k²).", practice: "∫ dx/(x²+2x-3)", practiceAns: "\\frac{1}{4}\\ln\\left|\\frac{x-1}{x+3}\\right| + C" }
    ]
};